//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonOptionRes.c"
#include "MenuCommonOption.h"
#include "PrjCfg.h"
#include "UIFlow.h"

#define __MODULE__          MenuCommonOption
//#define __DBGLVL__ 0        //OFF mode, show nothing
#define __DBGLVL__ 1        //ERROR mode, show err, wrn only
//#define __DBGLVL__ 2        //TRACE mode, show err, wrn, ind, msg and func and ind, msg and func can be filtering by __DBGFLT__ settings
#define __DBGFLT__ "*"      //*=All
#include "DebugModule.h"

//---------------------MenuCommonOptionCtrl Debug Definition -----------------------------
#define _MENUCOMMONOPTION_ERROR_MSG        1
#define _MENUCOMMONOPTION_TRACE_MSG        0

#if (_MENUCOMMONOPTION_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonOptionErrMsg(...)            debug_msg ("^R MenuCommonOption: "__VA_ARGS__)
#else
#define MenuCommonOptionErrMsg(...)
#endif

#if (_MENUCOMMONOPTION_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonOptionTraceMsg(...)          debug_msg ("^B MenuCommonOption: "__VA_ARGS__)
#else
#define MenuCommonOptionTraceMsg(...)
#endif

//---------------------MenuCommonOptionCtrl Global Variables -----------------------------
#define PRE_DUMMY_ITEM        2
#define MAX_SUPPROTED_ITEM   18
#define MENU_OPTION_HEIGHT   30

static INT32    g_TouchPressX;
static INT32    g_TouchPressY;
static INT32    g_PressedItem;
static INT32    g_MenuMoved;
static Ux_RECT  Menu_rect;
static INT32    EnabledItem;
static INT32    ItemReMap[PRE_DUMMY_ITEM + MAX_SUPPROTED_ITEM];

static TM_MENU* g_pTouchOptionMenu = 0;

//---------------------MenuCommonOptionCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonOptionCtrl Public API  ----------------------------------

//---------------------MenuCommonOptionCtrl Private API  ---------------------------------
static void MenuCommonOption_SetCurrentMenu(TM_MENU* pMenu)
{
    g_pTouchOptionMenu = pMenu;
}

static TM_MENU* MenuCommonOption_GetCurrentMenu(void)
{
    return g_pTouchOptionMenu;
}

//---------------------MenuCommonOptionCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption)
CTRL_LIST_ITEM(MenuCommonOption_STA_Title)
CTRL_LIST_ITEM(MenuCommonOption_PNL)
CTRL_LIST_ITEM(MenuCommonOption_MNU_Selection)
CTRL_LIST_ITEM(MenuCommonOption_BTN_OK)
CTRL_LIST_ITEM(MenuCommonOption_BTN_Cancel)
CTRL_LIST_END

//----------------------MenuCommonOptionCtrl Event---------------------------
INT32 MenuCommonOption_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnChildClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonOption_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonOption_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonOption_OnChildClose)
EVENT_END

INT32 MenuCommonOption_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    TM_OPTION*  pOption;
    UINT16      SelOption = 0;
    INT32       i;

    if(paramNum == 1)
    {
        // Get and store menu positon for move calculation.
        UxCtrl_GetPos((VControl *)&MenuCommonOption_MNU_SelectionCtrl,&Menu_rect);

        // Initial variables
        g_MenuMoved = FALSE;

        // Get current page/item/option
        MenuCommonOption_SetCurrentMenu((TM_MENU*)paramArray[0]);
        pMenu = MenuCommonOption_GetCurrentMenu();
        pPage = &pMenu->pPages[pMenu->SelPage];
        pItem = &pPage->pItems[pPage->SelItem];
        SelOption = SysGetFlag(pItem->SysFlag);

        // Update title
        UxStatic_SetData(&MenuCommonOption_STA_TitleCtrl, STATIC_VALUE, pItem->TextId);

        // Set total item number to max
        UxMenu_SetData(&MenuCommonOption_MNU_SelectionCtrl, MNU_TOTITM, (PRE_DUMMY_ITEM + MAX_SUPPROTED_ITEM));

        // Insert first two dummy options.
        for (EnabledItem = 0;EnabledItem < PRE_DUMMY_ITEM; EnabledItem ++)
        {
            UxMenu_SetItemData(&MenuCommonOption_MNU_SelectionCtrl, EnabledItem, MNUITM_STRID,  STRID_NULL_);
        }

        // Set 1st valid item to default current item in case selOption is invalid.
        UxMenu_SetData(&MenuCommonOption_MNU_SelectionCtrl, MNU_CURITM, EnabledItem);

        if (pItem->ItemId == IDM_VERSION)
        {
            UxMenu_SetItemData(&MenuCommonOption_MNU_SelectionCtrl, EnabledItem, MNUITM_STRID,  Txt_Pointer(Prj_GetVersionString()));
            EnabledItem ++;
        }
        else
        {
            // Add enabled options to menu
            for (i = 0; i < pItem->Count; i ++)
            {
                pOption = &pItem->pOptions[i];

                if ((pOption->Status & TM_OPTION_STATUS_MASK) == TM_OPTION_ENABLE)
                {
                    // Save option to ItemReMap[]
                    ItemReMap[EnabledItem] = i;

                    // Update string
                    if(pOption->TextId & STRID_USER_START)
                    {
                        UxMenu_SetItemData(&MenuCommonOption_MNU_SelectionCtrl, EnabledItem, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
                    }
                    else
                    {
                        UxMenu_SetItemData(&MenuCommonOption_MNU_SelectionCtrl, EnabledItem, MNUITM_STRID,  pOption->TextId);
                    }

                    // Update current item if match
                    if (i == SelOption)
                    {
                        UxMenu_SetData(&MenuCommonOption_MNU_SelectionCtrl, MNU_CURITM, EnabledItem);      // Set current item to correct one
                    }

                    EnabledItem ++;

                    // If exceed max support options, break and send warning message
                    if (EnabledItem >= (PRE_DUMMY_ITEM + MAX_SUPPROTED_ITEM))
                    {
                        DBG_WRN("Exceed max supported options!");
                        break;
                    }
                }
            }
        }
        // Update correct total item number
        UxMenu_SetData(&MenuCommonOption_MNU_SelectionCtrl, MNU_TOTITM, EnabledItem);
    }

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonOption_STA_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_STA_Title)
EVENT_END

//---------------------MenuCommonOption_PNLCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption_PNL)
CTRL_LIST_END

//----------------------MenuCommonOption_PNLCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_PNL)
EVENT_END

//----------------------MenuCommonOption_MNU_SelectionCtrl Event---------------------------
INT32 MenuCommonOption_MNU_Selection_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_MNU_Selection_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_MNU_Selection_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_MNU_Selection_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption_MNU_Selection)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonOption_MNU_Selection_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonOption_MNU_Selection_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonOption_MNU_Selection_OnTouchPanelMove)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonOption_MNU_Selection_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonOption_MNU_Selection_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // Store pressed coordinate and current item for move event calculation
    g_MenuMoved = FALSE;
    g_TouchPressX = paramArray[0];
    g_TouchPressY = paramArray[1];
    g_PressedItem = UxMenu_GetData(pCtrl, MNU_CURITM);

    // Do not trigger default press event in UICtrlMenuLib
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_MNU_Selection_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // Do not trigger default release event in UICtrlMenuLib
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_MNU_Selection_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiPosX;
    INT32 uiPosY;
    INT32 CurrItem;
    INT32 TatalItem;
    INT32 ItemOffset;

    g_MenuMoved = TRUE;
    uiPosX = paramArray[0];
    uiPosY = paramArray[1];

    // check whether the move point is in the menu range
    if ((uiPosY > Menu_rect.y1) && uiPosY < (Menu_rect.y1 + 5 * MENU_OPTION_HEIGHT))
    {
        // Calculate how many option range is crossed
        ItemOffset = (uiPosY - g_TouchPressY) / MENU_OPTION_HEIGHT;

        if (ItemOffset)
        {
            TatalItem = UxMenu_GetData(pCtrl, MNU_TOTITM);
            CurrItem = g_PressedItem - ItemOffset;
            // Check whether the target option is in valid range
            if (CurrItem >= PRE_DUMMY_ITEM && CurrItem < TatalItem)
            {
                UxMenu_SetData(pCtrl, MNU_CURITM, CurrItem);
                UxCtrl_SetDirty(&MenuCommonOption_PNLCtrl, TRUE);
                Ux_Redraw();
            }
        }
    }
    // Flush repeat NVTEVT_MOVE in event queue
    Ux_FlushEventByRange(NVTEVT_MOVE, NVTEVT_MOVE);

    // Do not trigger default move event in UICtrlMenuLib
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_MNU_Selection_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiPosX;
    INT32 uiPosY;
    INT32 CurrItem;
    INT32 TatalItem;
    INT32 ItemOffset;

    if (g_MenuMoved == FALSE)
    {
        uiPosX = paramArray[0];
        uiPosY = paramArray[1];

        ItemOffset = ((uiPosY - Menu_rect.y1) / MENU_OPTION_HEIGHT) - 2;
        if (ItemOffset)
        {
            TatalItem = UxMenu_GetData(pCtrl, MNU_TOTITM);
            CurrItem = UxMenu_GetData(pCtrl, MNU_CURITM);
            CurrItem = g_PressedItem + ItemOffset;
            // Check whether the target option is in valid range
            if (CurrItem >= PRE_DUMMY_ITEM && CurrItem < TatalItem)
            {
                UxMenu_SetData(pCtrl, MNU_CURITM, CurrItem);
                UxCtrl_SetDirty(&MenuCommonOption_PNLCtrl, TRUE);
                Ux_Redraw();
            }
        }
    }
    return NVTEVT_CONSUME;
}
//----------------------MenuCommonOption_BTN_OKCtrl Event---------------------------
INT32 MenuCommonOption_BTN_OK_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption_BTN_OK)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonOption_BTN_OK_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonOption_BTN_OK_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    UINT16      SelOption = 0;

    // Get menu/page/item
    pMenu = MenuCommonOption_GetCurrentMenu();
    pPage = &pMenu->pPages[pMenu->SelPage];
    pItem = &pPage->pItems[pPage->SelItem];

    // Save the option
    if (pItem->SysFlag)
    {
        // Remap select option to real one
        SelOption = ItemReMap[UxMenu_GetData(&MenuCommonOption_MNU_SelectionCtrl, MNU_CURITM)];
        SysSetFlag(pItem->SysFlag,SelOption);
        TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, SelOption));
    }
    Ux_CloseWindow (&MenuCommonOptionCtrl, 0);
    return NVTEVT_CONSUME;
}
//----------------------MenuCommonOption_BTN_CancelCtrl Event---------------------------
INT32 MenuCommonOption_BTN_Cancel_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption_BTN_Cancel)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonOption_BTN_Cancel_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonOption_BTN_Cancel_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // Just close window without save option
    Ux_CloseWindow (&MenuCommonOptionCtrl, 0);
    return NVTEVT_CONSUME;
}
