//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIFramework.h"

extern VControl MenuCommonOptionCtrl;//Panel type

extern VControl MenuCommonOption_STA_TitleCtrl;//Static type

extern VControl MenuCommonOption_PNLCtrl;//Panel type

extern VControl MenuCommonOption_MNU_SelectionCtrl;//Menu type

typedef enum
{
MenuCommonOption_MNU_Selection_STRID_0,
MenuCommonOption_MNU_Selection_STRID_1,
MenuCommonOption_MNU_Selection_STRID_2,
MenuCommonOption_MNU_Selection_STRID_3,
MenuCommonOption_MNU_Selection_STRID_4,
MenuCommonOption_MNU_Selection_MAX
}MenuCommonOption_MNU_Selection_Setting;

extern VControl MenuCommonOption_BTN_OKCtrl;//Button type

extern VControl MenuCommonOption_BTN_CancelCtrl;//Button type

//---------------------MenuCommonOptionCtrl User Export---------------------------
#endif
