//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONCONFIRM_H
#define MENUCOMMONCONFIRM_H

#include "UIFramework.h"

extern VControl MenuCommonConfirmCtrl;//Panel type

extern VControl MenuCommonConfirm_TitleCtrl;//Static type

extern VControl MenuCommonConfirm_BTN_YesCtrl;//Button type

extern VControl MenuCommonConfirm_BTN_NoCtrl;//Button type

//---------------------MenuCommonConfirmCtrl User Export---------------------------
#endif
