//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIFramework.h"

extern VControl MenuCommonItemCtrl;//Panel type

extern VControl MenuCommonItem_TitleCtrl;//Menu type

typedef enum
{
MenuCommonItem_Title_STRID_WIFI,
MenuCommonItem_Title_MAX
}MenuCommonItem_Title_Setting;

extern VControl MenuCommonItem_BTN0Ctrl;//Button type

extern VControl MenuCommonItem_BTN1Ctrl;//Button type

extern VControl MenuCommonItem_BTN2Ctrl;//Button type

extern VControl MenuCommonItem_BTN3Ctrl;//Button type

extern VControl MenuCommonItem_BTN4Ctrl;//Button type

extern VControl MenuCommonItem_BTN5Ctrl;//Button type

extern VControl MenuCommonItem_BTN6Ctrl;//Button type

extern VControl MenuCommonItem_BTN7Ctrl;//Button type

extern VControl MenuCommonItem_BTN8Ctrl;//Button type

extern VControl MenuCommonItem_BTN9Ctrl;//Button type

extern VControl MenuCommonItem_BTN10Ctrl;//Button type

extern VControl MenuCommonItem_BTN11Ctrl;//Button type

extern VControl MenuCommonItem_Point0Ctrl;//Panel type

extern VControl MenuCommonItem_Point1Ctrl;//Panel type

extern VControl MenuCommonItem_Point2Ctrl;//Panel type

extern VControl MenuCommonItem_Point3Ctrl;//Panel type

extern VControl MenuCommonItem_Point4Ctrl;//Panel type

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
