//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonConfirmRes.c"
#include "MenuCommonConfirm.h"
#include "PrjCfg.h"
#include "UIFlow.h"
#include "UIPlayComm.h"

//---------------------MenuCommonConfirmCtrl Debug Definition -----------------------------
#define _MENUCOMMONCONFIRM_ERROR_MSG        1
#define _MENUCOMMONCONFIRM_TRACE_MSG        0

#if (_MENUCOMMONCONFIRM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonConfirmErrMsg(...)            debug_msg ("^R MenuCommonConfirm: "__VA_ARGS__)
#else
#define MenuCommonConfirmErrMsg(...)
#endif

#if (_MENUCOMMONCONFIRM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonConfirmTraceMsg(...)          debug_msg ("^B MenuCommonConfirm: "__VA_ARGS__)
#else
#define MenuCommonConfirmTraceMsg(...)
#endif

//---------------------MenuCommonConfirmCtrl Global Variables -----------------------------
static UINT32 gBKGEvt = 0;
static UINT32 gExeEvt = 0;
static UINT32 gItemID = 0;

//---------------------MenuCommonConfirmCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonConfirmCtrl Public API  ----------------------------------

//---------------------MenuCommonConfirmCtrl Private API  ---------------------------------
//---------------------MenuCommonConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonConfirm)
CTRL_LIST_ITEM(MenuCommonConfirm_Title)
CTRL_LIST_ITEM(MenuCommonConfirm_BTN_Yes)
CTRL_LIST_ITEM(MenuCommonConfirm_BTN_No)
CTRL_LIST_END

//----------------------MenuCommonConfirmCtrl Event---------------------------
INT32 MenuCommonConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnTouchPanelSlideUp(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_SLIDE_UP,MenuCommonConfirm_OnTouchPanelSlideUp)
EVENT_END

INT32 MenuCommonConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 strID = 0;
    gBKGEvt = 0;
    gExeEvt = 0;
    if (paramNum == 1)
    {
        gItemID = paramArray[0];
        switch (gItemID)
        {
            case IDM_FORMAT:
                strID = STRID_DELETE_WARNING;
                gBKGEvt = NVTEVT_BKW_FORMAT_CARD;
                break;
            case IDM_DEFAULT:
                strID = STRID_RESET_WARNING;
                gExeEvt = NVTEVT_EXE_SYSRESET_NO_WIN;
                break;
            case IDM_FW_UPDATE:
                strID = STRID_FW_UPDATE;
                gBKGEvt = NVTEVT_BKW_FW_UPDATE;
                break;
            case IDM_DELETE_ALL:
                strID = STRID_ERASE_ALL;
                gBKGEvt = NVTEVT_BKW_DELALL;
                break;
            case IDM_PROTECT_ALL:
                strID = STRID_LOCKALL;
                AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ALL);
                gBKGEvt = NVTEVT_BKW_SETPROTECT;
                break;
            case IDM_UNPROTECT_ALL:
                strID = STRID_UNLOCKALL;
                AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ALL);
                gBKGEvt = NVTEVT_BKW_SETPROTECT;
                break;
            case IDM_PROTECT:
                strID = STRID_LOCKONE;
                AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ONE);
                gBKGEvt = NVTEVT_BKW_SETPROTECT;
                break;
            case IDM_DELETE_THIS:
                strID = STRID_ERASE_THIS;
                break;
            default:
                gBKGEvt = 0;
                MenuCommonConfirmErrMsg("error itemID %d\r\n",gItemID);
        }
    }

    if(gItemID == IDM_PROTECT)
    {
        UxButton_SetItemData(&MenuCommonConfirm_BTN_YesCtrl, 0, BTNITM_ICONID, ICON_LOCK_M);
        UxButton_SetItemData(&MenuCommonConfirm_BTN_NoCtrl, 0, BTNITM_ICONID, ICON_LOCK_UNLOCK_M);
    }
    else
    {
        UxButton_SetItemData(&MenuCommonConfirm_BTN_YesCtrl, 0, BTNITM_ICONID, ICON_OK_M);
        UxButton_SetItemData(&MenuCommonConfirm_BTN_NoCtrl, 0, BTNITM_ICONID, ICON_NO_M);
    }
    UxStatic_SetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE, strID);
    UI_SetDisplayPalette(LAYER_OSD1,0,256,gDemoKit_PaletteConfirm_Palette);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UI_SetDisplayPalette(LAYER_OSD1,0,256,gDemoKit_PaletteOption_Palette);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(((paramNum==2)&&(paramArray[0]==NVTRET_WAITMOMENT)) || (STRID_ERASE_THIS == UxStatic_GetData(&MenuCommonConfirm_TitleCtrl,STATIC_VALUE)))
    {
        Ux_CloseWindow(pCtrl,0);
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonConfirm_OnTouchPanelSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(pCtrl,0);
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonConfirm_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_Title)
EVENT_END

//----------------------MenuCommonConfirm_BTN_YesCtrl Event---------------------------
INT32 MenuCommonConfirm_BTN_Yes_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm_BTN_Yes)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonConfirm_BTN_Yes_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonConfirm_BTN_Yes_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (STRID_ERASE_THIS == UxStatic_GetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE))
    {
        UINT32 uiLockStatus;
        PB_GetParam(PBPRMID_FILE_ATTR_LOCK, &uiLockStatus);
        if(uiLockStatus)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_FILE_PROTECTED, FLOWWRNMSG_TIMER_1SEC);
            return NVTEVT_CONSUME;
        }
        UIPlay_Delete(PB_DELETE_ONE);
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
    }
    else if(gBKGEvt)
    {
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
        BKG_PostEvent(gBKGEvt);
    }
    else
    {
        Ux_SendEvent(&UISetupObjCtrl,gExeEvt, 0);
        Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonConfirm_BTN_NoCtrl Event---------------------------
INT32 MenuCommonConfirm_BTN_No_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm_BTN_No)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonConfirm_BTN_No_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonConfirm_BTN_No_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (gItemID == IDM_PROTECT)
    {
        AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ONE);
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
        BKG_PostEvent(gBKGEvt);
    }
    else
    {
        Ux_CloseWindow(&MenuCommonConfirmCtrl,0);
    }
    return NVTEVT_CONSUME;
}
