//This source code is generated by UI Designer Studio.

#ifndef FLOWIPCAM_H
#define FLOWIPCAM_H

#include "UIFramework.h"

extern VControl FlowIPCam_OsdFrameCtrl;//Panel type

extern VControl FlowIPCamCtrl;//Panel type

#endif
