//This source code is generated by UI Designer Studio.

#ifndef FLOWIPCAMRES_H
#define FLOWIPCAMRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------
SHOW_MAP_BEGIN(Skin9999)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin9999,0,0,847,479)

SHOW_MAP_BEGIN(FlowIPCam_OsdFrame)
SHOW_MAP_BODY(Skin9999)
SHOW_MAP_END

DECLARE_EVENT(FlowIPCam_OsdFrame)
DECLARE_CTRL_LIST(FlowIPCam_OsdFrame)
CREATE_CTRL(FlowIPCam_OsdFrame,FlowIPCam_OsdFrame,CTRL_WND,NULL,0 ,0,0,847,479)

SHOW_MAP_BEGIN(FlowIPCam)
SHOW_MAP_END

DECLARE_EVENT(FlowIPCam)
DECLARE_CTRL_LIST(FlowIPCam)
CREATE_CTRL(FlowIPCam,FlowIPCam,CTRL_WND,NULL,0 ,0,0,847,479)
#endif
