//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWRNMSG_H
#define UIFLOWWNDWRNMSG_H

#include "UIFramework.h"

extern VControl UIFlowWndWrnMsgCtrl;//Panel type 

extern VControl UIFlowWndWrnMsg_StaticTXT_MsgCtrl;//Static type 

extern VControl UIFlowWndWrnMsg_StaticTXT_FileNameCtrl;//Static type 

extern VControl UIFlowWndWrnMsg_StatusICN_DeleteCtrl;//Status type 

typedef enum
{
UIFlowWndWrnMsg_StatusICN_Delete_ICON_WARNING_DELETE_RELEASE,
UIFlowWndWrnMsg_StatusICN_Delete_ICON_WARNING_DELETE_PRESSED,
UIFlowWndWrnMsg_StatusICN_Delete_MAX
}UIFlowWndWrnMsg_StatusICN_Delete_Setting;

extern VControl UIFlowWndWrnMsg_StaticICN_FileErrorCtrl;//Static type 

extern VControl UIFlowWndWrnMsg_StatusICN_MovBwdCtrl;//Status type 

typedef enum
{
UIFlowWndWrnMsg_StatusICN_MovBwd_ICON_FB_LEFT,
UIFlowWndWrnMsg_StatusICN_MovBwd_ICON_FB_LEFT_PRESSED,
UIFlowWndWrnMsg_StatusICN_MovBwd_MAX
}UIFlowWndWrnMsg_StatusICN_MovBwd_Setting;

extern VControl UIFlowWndWrnMsg_StatusICN_MovFwdCtrl;//Status type 

typedef enum
{
UIFlowWndWrnMsg_StatusICN_MovFwd_ICON_FF_RIGHT,
UIFlowWndWrnMsg_StatusICN_MovFwd_ICON_FF_RIGHT_PRESSED,
UIFlowWndWrnMsg_StatusICN_MovFwd_MAX
}UIFlowWndWrnMsg_StatusICN_MovFwd_Setting;

//---------------------UIFlowWndWrnMsgCtrl User Export---------------------------
#endif
