//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayFileListRes.c"
#include "UIFlowWndPlayFileList.h"
#include "PrjCfg.h"
/* modify begin by ZMD, 2017-02-15 new version management*/
#if defined(YQCONFIG_ANDROID_SYSTEM_SUPPORT)
#include "UIFlow.h"

#include "UART_TO_MTK.h"
#include "FileDB.h"
#include "PlaybackTsk.h"

#define UIFLOW_FILELISTMODE_FEEDBACKTOMTK    0x02
typedef enum
{
    UIFLOW_LIST_TOUCH_KEY_NONE,
    UIFLOW_LIST_TOUCH_KEY_RETURN,
    UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE,
    UIFLOW_LIST_TOUCH_KEY_LASTMOVIE,
    UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO,
    UIFLOW_LIST_TOUCH_KEY_LASTPHOTO,
    UIFLOW_LIST_TOUCH_KEY_RO,
    UIFLOW_LIST_TOUCH_KEY_UPPAGE,
    UIFLOW_LIST_TOUCH_KEY_DOWNPAGE,
    UIFLOW_LIST_TOUCH_KEY_ITEM,
    UIFLOW_LIST_TOUCH_KEY_MAX
} UIFLOW_LIST_TOUCH_KEY;
static UIFLOW_LIST_TOUCH_KEY uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
static UIFLOW_LIST_TOUCH_KEY Key_Sort=UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE;

static UINT32 PlayFiletemIndex=0;
static UINT32 PlayFiletemIndexPre=0;

static BOOL PlayFileItemTPKeyHasPressed=FALSE;

static UINT32 guiTotalFile=0;
static UINT32 guiTotalFile_Sort=0;
static UINT32 guiTotalFile_FrontMovie=0;
static UINT32 guiTotalFile_LastMovie=0;
static UINT32 guiTotalFile_FrontPhoto=0;
static UINT32 guiTotalFile_LastPhoto=0;
static UINT32 guiTotalFile_RO=0;
static UINT16 Index_Array[128]= {0};
static UINT32 gTotalPage=1;
static UINT32 gCurrentPage=1;
static char item1_Buf[6][32];
#if defined(YQCONFIG_COMB_PLAYMODE_ITEMS_ONE_PAGE_OPTION_BIGSCREEN)
#define ITEMS_ONE_PAGE     5
#elif defined(YQCONFIG_COMB_PLAYMODE_ITEMS_ONE_PAGE_OPTION_SMALLSCREEN)
#define ITEMS_ONE_PAGE     6
#else
#define ITEMS_ONE_PAGE     6
#endif
#endif
/* modify end by ZMD, 2017-02-15 */
//---------------------UIFlowWndPlayFileListCtrl Debug Definition -----------------------------
#define _UIFLOWWNDPLAYFILELIST_ERROR_MSG        1
#define _UIFLOWWNDPLAYFILELIST_TRACE_MSG        0

#if (_UIFLOWWNDPLAYFILELIST_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndPlayFileListErrMsg(...)            debug_msg ("^R UIFlowWndPlayFileList: "__VA_ARGS__)
#else
#define UIFlowWndPlayFileListErrMsg(...)
#endif

#if (_UIFLOWWNDPLAYFILELIST_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndPlayFileListTraceMsg(...)          debug_msg ("^B UIFlowWndPlayFileList: "__VA_ARGS__)
#else
#define UIFlowWndPlayFileListTraceMsg(...)
#endif

//---------------------UIFlowWndPlayFileListCtrl Global Variables -----------------------------

//---------------------UIFlowWndPlayFileListCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndPlayFileListCtrl Public API  ----------------------------------

//---------------------UIFlowWndPlayFileListCtrl Private API  ---------------------------------
//---------------------UIFlowWndPlayFileListCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileList)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StaticTxt_Title)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Menu)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_Return)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_ScrollBar)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Panel)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPageNum)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_FrontMovie)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_FrontPhoto)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_LastMovie)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_LastPhoto)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_RO)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_UPPAGE)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_StatusIcon_DOWNPAGE)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListCtrl Event---------------------------
INT32 UIFlowWndPlayFileList_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnTouchPanelKey(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnMTKGpsInfo(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnStartMovieRecord(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnTimer(VControl *, UINT32, UINT32 *);


EVENT_BEGIN(UIFlowWndPlayFileList)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlayFileList_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlayFileList_OnClose)
EVENT_ITEM(NVTEVT_TOUCHPANEL_KEY,UIFlowWndPlayFileList_OnTouchPanelKey)
EVENT_ITEM(NVTEVT_MTK_GPSINFO,UIFlowWndPlayFileList_OnMTKGpsInfo)
EVENT_ITEM(NVTEVT_MTK_STARTREC,UIFlowWndPlayFileList_OnStartMovieRecord)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndPlayFileList_OnTimer)
EVENT_END

static UINT8 g_PageNumBuf[8];
void UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY Key1)
{
    UINT32 i,uiMenuItemIndex;
    UINT32 uiPBFileFmt, uiTotalItem;
    FILEDB_FILE_ATTR *pFileAttr;
    UINT32 uiOneLoop,uiStartIndex,uiEndIndex;
    UINT32 uiCurrentStep;
    //UINT32 uiPBFileFmt = 0;
    CHAR *ptr=NULL;
    UINT32 Temp_FileIndex=0;
    UINT32 Temp_Count=0;

    if(Key1==UIFLOW_LIST_TOUCH_KEY_NONE)
    {
    }
    else
    {
        Key_Sort=Key1;
    }
    //PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
    PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &guiTotalFile_Sort);
    //rootFolderLength = strlen(FILEDB_CARDV_ROOT);
    //uiPBFileFmt = AppPlay_GetData(PLAY_FILEFMT);
    debug_msg("^guiTotalFile_Sort:%d, ..\r\n",guiTotalFile_Sort);
    uiStartIndex=1;
    uiEndIndex=guiTotalFile_Sort+1;
    guiTotalFile_FrontMovie=0;
    guiTotalFile_LastMovie=0;
    guiTotalFile_LastPhoto=0;
    guiTotalFile_FrontPhoto=0;
    guiTotalFile_RO=0;
    memset((void*)Index_Array,0,sizeof(Index_Array));
    memset((void*)item1_Buf,0,sizeof(item1_Buf));

    if(gCurrentPage<1)
    {
        Temp_FileIndex=0;
    }
    else
    {
        Temp_FileIndex=(gCurrentPage-1)*ITEMS_ONE_PAGE;
    }

    for(i=uiStartIndex; i<uiEndIndex; i++)
    {
        pFileAttr = FileDB_SearhFile(0, (guiTotalFile_Sort-i));
        if (pFileAttr == NULL)
        {
            debug_msg("^RGetPathBySeq fails..!!!\r\n");
            //  return E_SYS;
            //for(i=0; i<ITEMS_ONE_PAGE; i++)
            //memset(item1_Buf[uiMenuItemIndex],0,32);
        }
        else
        {
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_RO)
            {
                ptr =strstr(pFileAttr->filePath,"RO");
                if(ptr)
                {
                    if((Temp_FileIndex<=guiTotalFile_RO)&&(guiTotalFile_RO<=Temp_FileIndex+ITEMS_ONE_PAGE))
                    {
                        Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                        Temp_Count++;
                    }
                    //   Index_Array[guiTotalFile_RO]=(UINT16)(guiTotalFile_Sort-i);
                    // debug_msg("^RLASTMOVIE:[%d]%d, %d ..%s..pFileAttr->fileType:%x..\r\n",(guiTotalFile_Sort-i),Index_Array[guiTotalFile_LastMovie],guiTotalFile_LastMovie,item1_Buf[1],pFileAttr->fileType);
                    guiTotalFile_RO++;
                    guiTotalFile=guiTotalFile_RO;
                }

                ptr =strstr(pFileAttr->filePath,"EMR");
                if(ptr)
                {
                    if((Temp_FileIndex<=guiTotalFile_RO)&&(guiTotalFile_RO<=Temp_FileIndex+ITEMS_ONE_PAGE))
                    {
                        Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                        Temp_Count++;
                    }
                    // Index_Array[guiTotalFile_RO]=(UINT16)(guiTotalFile_Sort-i);
                    // debug_msg("^RLASTMOVIE:[%d]%d, %d ..%s..pFileAttr->fileType:%x..\r\n",(guiTotalFile_Sort-i),Index_Array[guiTotalFile_LastMovie],guiTotalFile_LastMovie,item1_Buf[1],pFileAttr->fileType);
                    guiTotalFile_RO++;
                    guiTotalFile=guiTotalFile_RO;
                }
            }
            else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTMOVIE)
            {
                ptr =strstr(pFileAttr->filePath, "ie_Re");
                if(ptr)
                {
                    //  ptr =strstr(pFileAttr->filename,".MP4");
                    //  if(ptr)
                    {
                        if((Temp_FileIndex<=guiTotalFile_LastMovie)&&(guiTotalFile_LastMovie<=Temp_FileIndex+ITEMS_ONE_PAGE))
                        {
                            Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                            Temp_Count++;
                        }
                        //  Index_Array[guiTotalFile_LastMovie]=(UINT16)(guiTotalFile_Sort-i);
                        // debug_msg("^RLASTMOVIE:[%d]%d, %d ..%s..pFileAttr->fileType:%x..\r\n",(guiTotalFile_Sort-i),Index_Array[guiTotalFile_LastMovie],guiTotalFile_LastMovie,item1_Buf[1],pFileAttr->fileType);
                        guiTotalFile_LastMovie++;
                        guiTotalFile=guiTotalFile_LastMovie;
                    }
                }
            }
            else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTPHOTO)
            {
                ptr =strstr(pFileAttr->filePath, "Rear");
                if(ptr)
                {
                    ptr =strstr(pFileAttr->filename,".JPG");
                    if(ptr)
                    {
                        if((Temp_FileIndex<=guiTotalFile_LastPhoto)&&(guiTotalFile_LastPhoto<=Temp_FileIndex+ITEMS_ONE_PAGE))
                        {
                            Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                            Temp_Count++;
                        }
                        //  Index_Array[guiTotalFile_LastPhoto]=(UINT16)(guiTotalFile_Sort-i);
                        guiTotalFile_LastPhoto++;
                        guiTotalFile=guiTotalFile_LastPhoto;
                    }
                }
            }
            else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE)
            {
                ptr =strstr(pFileAttr->filePath, "ie_Fr");
                if(ptr)
                {
                    // ptr =strstr(pFileAttr->filename,".MP4");
                    // if(ptr)
                    {
                        if((Temp_FileIndex<=guiTotalFile_FrontMovie)&&(guiTotalFile_FrontMovie<=Temp_FileIndex+ITEMS_ONE_PAGE))
                        {
                            Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                            Temp_Count++;
                        }
                        // Index_Array[guiTotalFile_FrontMovie]=(UINT16)(guiTotalFile_Sort-i);
                        // debug_msg("^RFRONTMOVIE:[%d]%d, %d..%s..pFileAttr->fileType:%x..\r\n",(guiTotalFile_Sort-i),Index_Array[guiTotalFile_LastMovie],guiTotalFile_FrontMovie,item1_Buf[1],pFileAttr->fileType);
                        guiTotalFile_FrontMovie++;
                        guiTotalFile=guiTotalFile_FrontMovie;
                    }
                }
            }
            else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO)
            {
                ptr =strstr(pFileAttr->filePath, "Front");
                if(ptr)
                {
                    ptr =strstr(pFileAttr->filename,".JPG");
                    if(ptr)
                    {
                        if((Temp_FileIndex<=guiTotalFile_FrontPhoto)&&(guiTotalFile_FrontPhoto<=Temp_FileIndex+ITEMS_ONE_PAGE))
                        {
                            Index_Array[Temp_Count]=(UINT16)(guiTotalFile_Sort-i);
                            Temp_Count++;
                        }
                        //Index_Array[guiTotalFile_FrontPhoto]=(UINT16)(guiTotalFile_Sort-i);
                        guiTotalFile_FrontPhoto++;
                        guiTotalFile=guiTotalFile_FrontPhoto;
                    }
                }
            }

        }
    }



    if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE)
    {
        // guiTotalFile=guiTotalFile_FrontMovie;
        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE_PRESSED);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        //UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
        //  UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
    }
    else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTMOVIE)
    {
        //guiTotalFile=guiTotalFile_LastMovie;
        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE_PRESSED);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        // UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
        //  UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
    }
    else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO)
    {
        //guiTotalFile=guiTotalFile_FrontPhoto;
        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO_PRESSED);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        //   UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
        //  UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
    }
    else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTPHOTO)
    {
        //  guiTotalFile=guiTotalFile_LastPhoto;
        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO_PRESSED);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        //  UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
        //    UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
    }
    else if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_RO)
    {
        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO_PRESSED);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

        UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
        UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

        //   UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
        //    UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
    }
    else
    {

    }


    gTotalPage=(guiTotalFile%ITEMS_ONE_PAGE==0)?guiTotalFile/ITEMS_ONE_PAGE:guiTotalFile/ITEMS_ONE_PAGE+1;
    debug_msg("guiTotalFile:%d,gCurrentPage:%d, gTotalPage:%d, ..\r\n",guiTotalFile,gCurrentPage,gTotalPage);

    UxMenu_SetData(&UIFlowWndPlayFileList_MenuCtrl, MNU_CURITM, 0);

    if(gCurrentPage==gTotalPage)
    {
        uiTotalItem=guiTotalFile%ITEMS_ONE_PAGE;
//pgl 20160722 add to fix bug beg
        if(uiTotalItem==0)
        {
            uiTotalItem = ITEMS_ONE_PAGE;
        }
//pgl 20160722 add to fix bug end
    }
    else
    {
        uiTotalItem=ITEMS_ONE_PAGE;
    }

    if(guiTotalFile==0)
    {
        uiTotalItem=1;
    }
    UxMenu_SetData(&UIFlowWndPlayFileList_MenuCtrl, MNU_TOTITM, uiTotalItem);


    uiStartIndex=(gCurrentPage-1)*ITEMS_ONE_PAGE+1;

    if(gCurrentPage<gTotalPage)
    {
        uiEndIndex=gCurrentPage*ITEMS_ONE_PAGE+1;
    }
    else
    {
        uiEndIndex=guiTotalFile+1;
    }

    uiMenuItemIndex=0;


    for(i=uiStartIndex; i<uiEndIndex; i++)
    {
        // pFileAttr = FileDB_SearhFile(0, (guiTotalFile-i));
        //  pFileAttr = FileDB_SearhFile(0, Index_Array[(guiTotalFile-i)]);
        // pFileAttr = FileDB_SearhFile(0, Index_Array[(i-1)]);
        pFileAttr = FileDB_SearhFile(0, Index_Array[(i-uiStartIndex)]);

        if (pFileAttr == NULL)
        {
            for(i=0; i<ITEMS_ONE_PAGE; i++)
                memset(item1_Buf[uiMenuItemIndex],0,32);
        }
        else
        {
            snprintf(item1_Buf[uiMenuItemIndex],32,"%s",pFileAttr->filename);
            // debug_msg("[%d]:%s..pFileAttr->fileType:%x\r\n",(i-uiStartIndex),item1_Buf[uiMenuItemIndex],pFileAttr->fileType);
        }
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, uiMenuItemIndex, MNUITM_STRID,Txt_Pointer(item1_Buf[uiMenuItemIndex]));
        if((pFileAttr->fileType == FILEDB_FMT_MP4) || (pFileAttr->fileType == FILEDB_FMT_MOV)||(pFileAttr->fileType == FILEDB_FMT_AVI)||(pFileAttr->fileType == FILEDB_FMT_TS))
        {
            UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, uiMenuItemIndex, MNUITM_ICONID, ICON_FILE_VIDEO);
        }
        else
        {
            UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, uiMenuItemIndex, MNUITM_ICONID, ICON_SCENE_MODE_PORTRIAL);
        }
        uiMenuItemIndex++;
    }

    if(guiTotalFile==0)
    {
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, 0, MNUITM_STRID,Txt_Pointer(item1_Buf[uiMenuItemIndex]));
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, 0, MNUITM_ICONID, ICON_FILE_ERROR);
    }

    for(i=0; i<uiTotalItem; i++)
    {
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
    }
    if((PlayFiletemIndexPre>=0)&&(PlayFiletemIndexPre<ITEMS_ONE_PAGE))
    {
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, (STATUS_DISABLE| STATUS_FOCUS_BIT));
    }
    else
    {
        UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, 0, MNUITM_STATUS, (STATUS_DISABLE| STATUS_FOCUS_BIT));
    }
    /*
    if(gTotalPage==1)
    {
    		UxCtrl_SetShow(&UIFlowWndPlayFileList_PanelCtrl, TRUE);
    }
    else
    {
    	UxCtrl_SetShow(&UIFlowWndPlayFileList_PanelCtrl, FALSE);
    }
    */
    if(gTotalPage==gCurrentPage)
    {
        UxScrollBar_SetData(&UIFlowWndPlayFileList_StatusIcon_ScrollBarCtrl,SCRBAR_CURSTP,19);
    }
    else if(1==gCurrentPage)
    {
        UxScrollBar_SetData(&UIFlowWndPlayFileList_StatusIcon_ScrollBarCtrl,SCRBAR_CURSTP,0);
    }
    else
    {
        uiCurrentStep=(gCurrentPage*20)/gTotalPage;
        debug_msg("uiCurrentStep:%d..\r\n",uiCurrentStep);
        UxScrollBar_SetData(&UIFlowWndPlayFileList_StatusIcon_ScrollBarCtrl,SCRBAR_CURSTP,uiCurrentStep);
    }
    sprintf((char *)g_PageNumBuf, "%ld/%ld", gCurrentPage, gTotalPage);
    UxStatic_SetData(&UIFlowWndPlayFileListPageNumCtrl, STATIC_VALUE, Txt_Pointer(g_PageNumBuf));
    UxCtrl_SetShow(&UIFlowWndPlayFileListPageNumCtrl, TRUE);
    UxCtrl_SetDirty(&MenuCommonItem_PageNumCtrl, TRUE);

    UxCtrl_SetDirty(&UIFlowWndPlayFileListCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndPlayFileList_PanelCtrl, FALSE);

}


INT32 UIFlowWndPlayFileList_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    static BOOL firstPowerOn=TRUE;
    if(firstPowerOn==TRUE)
    {
        gCurrentPage=1;
    }
    UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
    //UIFlowWndPlayFileList_UpdateContent();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayFileList_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
#if !defined(YQCONFIG_TOUCH_TO_MTK_PLAYSOUND_OPTION)
INT32 UIFlowWndPlayFileList_OnTouchPanelKey(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiPositon,P1,P2;
    UINT32 FrameID;
    UINT32 TouchKeyStatus=0xFFFF;

    UINT32  uiSoundMask,uiSelect;
    UINT8   uiResqData[16]= {0};
    UINT32 uiJpegWidth, uiJpegHeight, uiDAR, uiMovieSize;
    UINT32 uiIndex=0;
    UINT32 uiStatus;
    UINT32 Temp=0;

    if(paramNum>0)
        TouchKeyStatus= paramArray[0];
    if(paramNum>1)
    {
        uiPositon= paramArray[1];
        P1=(uiPositon&0xFFFF0000)>>16;
        P2=(uiPositon&0x0000FFFF);
    }

    if(paramNum>2)
        FrameID=paramArray[2];

    switch(TouchKeyStatus)
    {
    case TOUCH_KEY_STATUS_PRESSED:
        if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_RETURN;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_LASTMOVIE;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_LASTPHOTO;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_RO;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_UPPAGE;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_UPPAGE_ICON_UPPAGE_PRESS);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_DOWNPAGE;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_DOWNPAGE_ICON_DOWNPAGE_PRESS);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl, TRUE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        else if(TPIsOnRangeMenu(&UIFlowWndPlayFileList_MenuCtrl,P1,P2)==TRUE)
        {
            uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
            if(uiStatus & PB_STA_DONE)
            {

            }
            else
            {
                debug_msg("Playback mode flush Event..\r\n");
                Ux_FlushEvent();
            }
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_ITEM;
            PlayFiletemIndex = TP_PhaseMenuItem_Index(&UIFlowWndPlayFileList_MenuCtrl,P2);
            PlayFiletemIndexPre=PlayFiletemIndex;
            debug_msg("PlayFiletemIndexPre:%d,PlayFiletemIndex:%d...\r\n",PlayFiletemIndexPre,PlayFiletemIndex);
            if((PlayFiletemIndex>=0)&&(PlayFiletemIndex<ITEMS_ONE_PAGE))
            {
                UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndex, MNUITM_STATUS, (STATUS_DISABLE| STATUS_FOCUS_BIT));
            }
            else
            {
                PlayFiletemIndex=0;
            }
        }
        else
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
        }
        break;

    case TOUCH_KEY_STATUS_RELEASED:
        if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_RETURN)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
                Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {
                //UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE_PRESSED);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                //		UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                //  UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
                //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE)
                {

                }
                else
                {
                    gCurrentPage=1;
                    guiTotalFile=0;
                }
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE);

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_LASTMOVIE)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE_PRESSED);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                //  UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

                //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTMOVIE)
                {

                }
                else
                {
                    gCurrentPage=1;
                    guiTotalFile=0;
                }
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_LASTMOVIE);

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO_PRESSED);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                // UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
                //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO)
                {

                }
                else
                {
                    gCurrentPage=1;
                    guiTotalFile=0;
                }
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO);

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_LASTPHOTO)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO_PRESSED);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                //  UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                //   UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
                //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTPHOTO)
                {

                }
                else
                {
                    gCurrentPage=1;
                    guiTotalFile=0;
                }
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_LASTPHOTO);

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_RO)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO_PRESSED);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

                // UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
                //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
                if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_RO)
                {
                }
                else
                {
                    gCurrentPage=1;
                    guiTotalFile=0;
                }
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_RO);

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_UPPAGE)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_UPPAGE_ICON_UPPAGE_RELEASE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl, TRUE);

                if(gCurrentPage>1)
                {
                    gCurrentPage--;
                    UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
                }

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_DOWNPAGE)
            {
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_DOWNPAGE_ICON_DOWNPAGE_RELEASE);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl, TRUE);

                if(gCurrentPage<gTotalPage)
                {
                    gCurrentPage++;
                    UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
                }

                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else if(TPIsOnRangeMenu(&UIFlowWndPlayFileList_MenuCtrl,P1,P2)==TRUE)
        {
            if(uiPlaybackKeyListPressed==UIFLOW_LIST_TOUCH_KEY_ITEM)
            {
                PlayFiletemIndex = TP_PhaseMenuItem_Index(&UIFlowWndPlayFileList_MenuCtrl,P2);
                debug_msg("PlayFiletemIndexPre:%d,PlayFiletemIndex:%d...\r\n",PlayFiletemIndexPre,PlayFiletemIndex);
                if(PlayFiletemIndex==PlayFiletemIndexPre)
                {
                    UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndex, MNUITM_STATUS, STATUS_ENABLE);            // return to 1st item
                    if(guiTotalFile!=0)
                    {
                        //Temp= guiTotalFile-(((gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex)+1);//Descending Index
                        // Temp= (((gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex)+1)-1;// ascending index
                        Temp= PlayFiletemIndex;// ascending index
                        uiIndex= Index_Array[Temp]+1;//(gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex;
                        //(_MODEL_DSC_ == _MODEL_PWU01_)
                        //uiIndex=(gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex;
                        debug_msg("uiIndex:%d,Temp:%d...\r\n",uiIndex,Temp);
                        Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,2,NVTRET_THUMBNAIL,uiIndex);
                    }
                }
                else
                {
                    UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
                }
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
            else
            {
                UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
                UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
                UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
                uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
                MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
            }
        }
        else
        {
            UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
        break;

    case TOUCH_GESTURE_DOWN2UP:
        if(gCurrentPage<gTotalPage)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
            gCurrentPage++;
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            //(_MODEL_DSC_ == _MODEL_PWU01_)
            // UIFlowWndPlayFileList_UpdateContent();
        }
        break;

    case TOUCH_GESTURE_UP2DOWN:
        if(gCurrentPage>1)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
            gCurrentPage--;
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            //(_MODEL_DSC_ == _MODEL_PWU01_)
            //UIFlowWndPlayFileList_UpdateContent();
        }
        break;
    }

    return NVTEVT_CONSUME;
}
#else
INT32 UIFlowWndPlayFileList_OnTouchPanelKey(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiPositon,P1,P2;
    UINT32 FrameID;
    UINT32 TouchKeyStatus=0xFFFF;

    UINT32  uiSoundMask,uiSelect;
    UINT8   uiResqData[16]= {0};
    UINT32 uiJpegWidth, uiJpegHeight, uiDAR, uiMovieSize;
    UINT32 uiIndex=0;
    UINT32 uiStatus;
    UINT32 Temp=0;

    if(paramNum>0)
        TouchKeyStatus= paramArray[0];
    if(paramNum>1)
    {
        uiPositon= paramArray[1];
        P1=(uiPositon&0xFFFF0000)>>16;
        P2=(uiPositon&0x0000FFFF);
    }

    if(paramNum>2)
        FrameID=paramArray[2];

    switch(TouchKeyStatus)
    {
    // case TOUCH_KEY_STATUS_PRESSED:
    case TOUCH_KEY_STATUS_RELEASED:
        if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,P1,P2)==TRUE)
        {

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
            Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,P1,P2)==TRUE)
        {
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            //		UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
            //  UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
            //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE)
            {

            }
            else
            {
                gCurrentPage=1;
                guiTotalFile=0;
            }
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_FRONTMOVIE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,P1,P2)==TRUE)
        {
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            //  UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
            // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

            //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTMOVIE)
            {

            }
            else
            {
                gCurrentPage=1;
                guiTotalFile=0;
            }
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_LASTMOVIE);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,P1,P2)==TRUE)
        {

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            // UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
            // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
            //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO)
            {

            }
            else
            {
                gCurrentPage=1;
                guiTotalFile=0;
            }
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_FRONTPHOTO);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,P1,P2)==TRUE)
        {

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            //  UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
            //   UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
            //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_LASTPHOTO)
            {

            }
            else
            {
                gCurrentPage=1;
                guiTotalFile=0;
            }
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_LASTPHOTO);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,P1,P2)==TRUE)
        {

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO_PRESSED);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontMovie_ICON_TP_MENU_FRONTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastMovie_ICON_TP_MENU_LASTMOVIE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_FrontPhoto_ICON_TP_MENU_FRONTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_LastPhoto_ICON_TP_MENU_LASTPHOTO);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl, TRUE);

            // UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ROCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_RO_ICON_TP_MENU_RO);
            // UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ROCtrl, TRUE);
            //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);
            if(Key_Sort==UIFLOW_LIST_TOUCH_KEY_RO)
            {
            }
            else
            {
                gCurrentPage=1;
                guiTotalFile=0;
            }
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_RO);

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,P1,P2)==TRUE)
        {

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_UPPAGE_ICON_UPPAGE_PRESS);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl, TRUE);

            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_UPPAGE_ICON_UPPAGE_RELEASE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl, TRUE);

            if(gCurrentPage>1)
            {
                gCurrentPage--;
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            }

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRange(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,P1,P2)==TRUE)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_DOWNPAGE;
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_DOWNPAGE_ICON_DOWNPAGE_PRESS);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl, TRUE);


            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_DOWNPAGE_ICON_DOWNPAGE_RELEASE);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl, TRUE);

            if(gCurrentPage<gTotalPage)
            {
                gCurrentPage++;
                UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            }

            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else if(TPIsOnRangeMenu(&UIFlowWndPlayFileList_MenuCtrl,P1,P2)==TRUE)
        {
            uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
            if(uiStatus & PB_STA_DONE)
            {

            }
            else
            {
                debug_msg("Playback mode flush Event..\r\n");
                Ux_FlushEvent();
            }

            PlayFiletemIndex = TP_PhaseMenuItem_Index(&UIFlowWndPlayFileList_MenuCtrl,P2);
            PlayFiletemIndexPre=PlayFiletemIndex;
            debug_msg("PlayFiletemIndexPre:%d,PlayFiletemIndex:%d...\r\n",PlayFiletemIndexPre,PlayFiletemIndex);
            if((PlayFiletemIndex>=0)&&(PlayFiletemIndex<ITEMS_ONE_PAGE))
            {
                UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndex, MNUITM_STATUS, (STATUS_DISABLE| STATUS_FOCUS_BIT));
            }
            else
            {
                PlayFiletemIndex=0;
            }


            PlayFiletemIndex = TP_PhaseMenuItem_Index(&UIFlowWndPlayFileList_MenuCtrl,P2);
            debug_msg("PlayFiletemIndexPre:%d,PlayFiletemIndex:%d...\r\n",PlayFiletemIndexPre,PlayFiletemIndex);
            if(PlayFiletemIndex==PlayFiletemIndexPre)
            {
                UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndex, MNUITM_STATUS, STATUS_ENABLE);            // return to 1st item
                if(guiTotalFile!=0)
                {
                    //Temp= guiTotalFile-(((gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex)+1);//Descending Index
                    // Temp= (((gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex)+1)-1;// ascending index
                    Temp= PlayFiletemIndex;// ascending index
                    uiIndex= Index_Array[Temp]+1;//(gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex;
                    //(_MODEL_DSC_ == _MODEL_PWU01_)
                    //uiIndex=(gCurrentPage-1)*ITEMS_ONE_PAGE+PlayFiletemIndex;
                    debug_msg("uiIndex:%d,Temp:%d...\r\n",uiIndex,Temp);
                    Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,2,NVTRET_THUMBNAIL,uiIndex);
                }
            }
            else
            {
                UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
            }
            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);

        }
        else
        {
            UxMenu_SetItemData(&UIFlowWndPlayFileList_MenuCtrl, PlayFiletemIndexPre, MNUITM_STATUS, STATUS_ENABLE);
            UxState_SetData(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl,STATE_CURITEM,UIFlowWndPlayFileList_StatusIcon_Return_ICON_TP_MENU_RETURN);
            UxCtrl_SetShow(&UIFlowWndPlayFileList_StatusIcon_ReturnCtrl, TRUE);
            uiResqData[0]=UIFLOW_FILELISTMODE_FEEDBACKTOMTK;
            MTKComposeCMDRspFrame(FrameID, CMD_TOUCH,(UINT8 *)&uiResqData, 1);
        }
        uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
        break;

    case TOUCH_GESTURE_DOWN2UP:
        if(gCurrentPage<gTotalPage)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
            gCurrentPage++;
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            //(_MODEL_DSC_ == _MODEL_PWU01_)
            // UIFlowWndPlayFileList_UpdateContent();
        }
        break;

    case TOUCH_GESTURE_UP2DOWN:
        if(gCurrentPage>1)
        {
            uiPlaybackKeyListPressed=UIFLOW_LIST_TOUCH_KEY_NONE;
            gCurrentPage--;
            UIFlowWndPlayFileList_UpdateContent(UIFLOW_LIST_TOUCH_KEY_NONE);
            //(_MODEL_DSC_ == _MODEL_PWU01_)
            //UIFlowWndPlayFileList_UpdateContent();
        }
        break;
    }

    return NVTEVT_CONSUME;
}
#endif
extern BOOL System_GetSensor2Plug(void);//pgl 20160905 add

INT32 UIFlowWndPlayFileList_OnMTKGpsInfo(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT8   uiResqData[16]= {0};
    UINT32 FrameID;

    //debug_msg("UIFlowWndPlayFileList_OnMTKGPSInfo----entry----\r\n");
    if(paramNum>0)
        FrameID=paramArray[0];
    /*
    result:  0--success¡ê? 1----fail
    deflection:  0---normal,   1----right,   2-----left
    front_car_warning:  0---no warning,  1---warning
    stop_go:  0---stop,   1---go
    curr_mode:  0---recording,   1---camera,   2---palyback
    */
//pgl_modify begin
    #if 0
    switch(g_PlbData.State)
    {
    case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        uiResqData[0]=0x80;
        break;

    case PLB_ST_FULL:
    case PLB_ST_PAUSE_MOV:
        uiResqData[0]=0x00;
        break;
    }
    #else
    uiResqData[0]=0x00;
    #endif
//pgl_modify end
//pgl 20160905 add beg
    if(System_GetSensor2Plug())
    {
        uiResqData[1] = 0x01;
    }
    else
    {
        uiResqData[1] = 0x0;
    }
//pgl 20160905 add end

    MTKComposeCMDRspFrame(FrameID, CMD_GPS,(UINT8 *)&uiResqData, 2/*1*/);	//pgl modify 20160905
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayFileList_OnStartMovieRecord(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT8   uiResqData[16]= {0};
    UINT32 FrameID;

    if(paramNum>0)
        FrameID=paramArray[0];


    UIFlowwndMovieSetNeedToRecordFlag(TRUE);
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);

    uiResqData[0]=0;
    MTKComposeCMDRspFrame(FrameID, CMD_MOVIE_START,&uiResqData, 1);

    return NVTEVT_CONSUME;
}
/* modify begin by ZMD, 2017-02-15 new version management*/
#if defined(YQCONFIG_COMB_DET_BACKCAR_BY_GPIO)
extern BOOL DetBack_Flag;
extern BOOL Reverse_Flag;
#endif
/* modify end by ZMD, 2017-02-15 */
INT32 UIFlowWndPlayFileList_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    UINT32 uiStatus;

    uiEvent = paramNum ? paramArray[0] : 0;
    switch(uiEvent)
    {
    case NVTEVT_01SEC_TIMER:

        break;


    case NVTEVT_1SEC_TIMER:
        //debug_msg("PlayFileList timer: %d\r\n",1);
        /* modify begin by ZMD, 2017-02-15 new version management*/
        #if defined(YQCONFIG_COMB_DET_BACKCAR_BY_GPIO)
        if(DetBack_Flag==TRUE)
        {
            //DetBack_Flag=FALSE;

            Ux_CloseWindow(&UIFlowWndPlayFileListCtrl,0);

            //Reverse_Flag=TRUE;
        }
        #endif
        /* modify end by ZMD, 2017-02-15 */

        break;

    }
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayFileList_StaticTxt_TitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StaticTxt_Title)
EVENT_END

//----------------------UIFlowWndPlayFileList_MenuCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Menu)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_Return)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_ScrollBarCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_ScrollBar)
EVENT_END

//---------------------UIFlowWndPlayFileList_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileList_Panel)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileList_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Panel)
EVENT_END

//----------------------UIFlowWndPlayFileListPageNumCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPageNum)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_FrontMovieCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_FrontMovie)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_FrontPhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_FrontPhoto)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_LastMovieCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_LastMovie)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_LastPhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_LastPhoto)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_ROCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_RO)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_UPPAGECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_UPPAGE)
EVENT_END

//----------------------UIFlowWndPlayFileList_StatusIcon_DOWNPAGECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_StatusIcon_DOWNPAGE)
EVENT_END

