#ifndef _UCTRLAPP_EVENT_H
#define _UCTRLAPP_EVENT_H
#include "Type.h"

#define TRIGGER_TRUE "TRIGGER_TRUE"
#define TRIGGER_FALSE "TRIGGER_FALSE"
#define TRIGGER_ERROR "TRIGGER_ERROR"
#define ALARM_HIGH    "HIGH"
#define ALARM_LOW     "LOW"

#define ALARM1_HIGH "DI0,1"
#define ALARM1_LOW "DI0,0"
#define MOTION1_TRIGGER "MD0,1"
#define MOTION1_NOTRIGGER "MD0,0"
#define TAMPER1_TRIGGER "TD0,1"
#define TAMPER1_NOTRIGGER "TD0,0"
#define ALARM_OUTPUT_SET_OK "OK"
#define ALARM_OUTPUT_OPEN_CMD "OPEN"
#define ALARM_OUTPUT_GROUNDED_CMD "GROUNDED"
#define ALARM_OUTPUT_OPEN "DO0,OPEN"
#define ALARM_OUTPUT_GROUNDED "DO0,grounded"
typedef enum { EVT_MOTION, EVT_ALARM_LEVEL_LOW, EVT_ALARM_LEVEL_HIGH} EVT_ALARM_TYPE;

extern void register_event(void);
#endif //_UCTRLAPP_EVENT_H