//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayConfirmDelRes.c"
#include "UIFlow.h"
#include "UIPlayComm.h"
#if defined(YQCONFIG_UART_TO_MTK_SUPPORT)
#include "UART_TO_MTK.h"
#endif
#if defined(YQCONFIG_ANDROID_SYSTEM_SUPPORT)
extern BOOL gbNTK96663Alive;
static UINT32 uiMenuPlayConfirmDelIndex=0;
static BOOL gbFileFlag=FALSE;
extern UINT32 gbTouchKeyIndex;
#endif
//---------------------UIMenuWndPlayConfirmDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDelCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyMode(VControl *, UINT32, UINT32 *);
//INT32 UIMenuWndPlayConfirmDel_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayConfirmDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayConfirmDel_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayConfirmDel_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayConfirmDel_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayConfirmDel_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayConfirmDel_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlayConfirmDel_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/05#Chris Chung -begin
    UxMenu_SetData(&UIMenuWndPlayConfirmDel_MenuCtrl, MNU_CURITM, 0);

    if(paramNum > 0)
    {
        UxState_SetData(&UIMenuWndPlayConfirmDel_StatusTextCtrl,STATE_CURITEM,paramArray[0]);
    }
    else
    {
        debug_msg("UIMenuWndPlayConfirmDel_OnOpen: param error\r\n");
    }
    //#NT#2009/08/05#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && (paramArray[1]==NVTRET_DELETEALL||paramArray[1]==NVTRET_DELETE))
        {
            UIPlay_PlaySingle(PB_SINGLE_CURR);
            Ux_CloseWindow((VControl *)(&UIMenuWndPlayDelCtrl), 0);
        }
    }
    else
    {
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayDelCtrl), 0);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayConfirmDelCtrl), 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayConfirmDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Menu)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_StatusText)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayConfirmDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Menu)
EVENT_ITEM(NVTEVT_KEY_NEXT,UIMenuWndPlayConfirmDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_SELECT,UIMenuWndPlayConfirmDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiLockStatus;

    //#NT#2009/08/05#Chris Chung -begin
    if(UxMenu_GetData(pCtrl,MNU_CURITM)==UIMenuWndPlayConfirmDel_Menu_STRID_OK)
    {
        if(UIStorageCheck(STORAGE_CHECK_LOCKED, NULL) == TRUE)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_1SEC);
            return NVTEVT_CONSUME;
        }

        switch(UxState_GetData(&UIMenuWndPlayConfirmDel_StatusTextCtrl,STATE_CURITEM))
        {
 
        default:
            debug_err(("UIMenuWndPlayConfirmDel_Menu_OnKeyEnter: status text error\r\n"));
        }
    }
    else
    {
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayDelCtrl), 0);
    }
    //#NT#2009/08/05#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayConfirmDel_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_StatusText)
EVENT_END

