//This source code is generated by UI Designer Studio.

#include <stdio.h>
#include "UIFlow.h"
#include "rtc.h"

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupDateTimeRes.c"
#include "UIMenuWndSetupDateTime.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupDateTimeCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPDATETIME_ERROR_MSG        1
#define _UIMENUWNDSETUPDATETIME_TRACE_MSG        0

#if (_UIMENUWNDSETUPDATETIME_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupDateTimeErrMsg(...)            debug_msg ("^R UIMenuWndSetupDateTime: "__VA_ARGS__)
#else
#define UIMenuWndSetupDateTimeErrMsg(...)
#endif

#if (_UIMENUWNDSETUPDATETIME_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupDateTimeTraceMsg(...)          debug_msg ("^B UIMenuWndSetupDateTime: "__VA_ARGS__)
#else
#define UIMenuWndSetupDateTimeTraceMsg(...)
#endif

//---------------------UIMenuWndSetupDateTimeCtrl Global Variables -----------------------------
#define DATETIME_MAX_YEAR       2050
#define DATETIME_DEFAULT_YEAR   2012
#define DATETIME_DEFAULT_MONTH     1
#define DATETIME_DEFAULT_DAY       1
#define DATETIME_DEFAULT_HOUR      0
#define DATETIME_DEFAULT_MINUTE    0
#define DATETIME_DEFAULT_SECOND    0

static UINT32 g_uiBlinkTimerID = NULL_TIMER;
static VControl* g_pActiveSettingCtrl = NULL;
static BOOL ShowActiveSetting = TRUE;

//---------------------UIMenuWndSetupDateTimeCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupDateTimeCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupDateTimeCtrl Private API  ---------------------------------

//---------------------UIMenuWndSetupDateTimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_Tab)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTimeCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDateTime_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDateTime_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDateTime_OnTouchPanelSlideUp(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupDateTime_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupDateTime_OnClose)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndSetupDateTime_OnTimer)
EVENT_ITEM(NVTEVT_SLIDE_UP,UIMenuWndSetupDateTime_OnTouchPanelSlideUp)
EVENT_END

static UINT32 g_year=DATETIME_DEFAULT_YEAR, g_month=DATETIME_DEFAULT_MONTH, g_day=DATETIME_DEFAULT_DAY;
static UINT32 g_hour=DATETIME_DEFAULT_HOUR, g_min=DATETIME_DEFAULT_MINUTE, g_second=DATETIME_DEFAULT_SECOND;
static char   itemY_Buf[32] = "0";
static char   itemY2_Buf[32] = "0";
static char   itemY3_Buf[32] = "0";
static char   itemY4_Buf[32] = "0";
static char   itemM_Buf[32] = "0";
static char   itemM2_Buf[32] = "0";
static char   itemD_Buf[32] = "0";
static char   itemD2_Buf[32] = "0";
static char   itemHR_Buf[32] = "0";
static char   itemHR2_Buf[32] = "0";
static char   itemMIN_Buf[32] = "0";
static char   itemMIN2_Buf[32] = "0";
static char   itemSEC_Buf[32] = "0";
static char   itemOther0_Buf[32] = "/";
static char   itemOther2_Buf[32] = ":";

_ALIGNED(4) static const UINT8 DayOfMonth[2][12] =
{
    // Not leap year
    {31,28,31,30,31,30,31,31,30,31,30,31},
    // Leap year
    {31,29,31,30,31,30,31,31,30,31,30,31}
};


static void UIMenuWndSetupDateTime_UpdateInfo(void)
{
    if(g_day > DayOfMonth[rtc_isLeapYear(g_year)][g_month-1])
        g_day = DayOfMonth[rtc_isLeapYear(g_year)][g_month-1];

    snprintf(itemY_Buf, 32, "%1ld", g_year/1000);
    snprintf(itemY2_Buf, 32, "%01ld", (g_year/100)%10);
    snprintf(itemY3_Buf, 32, "%01ld", (g_year/10)%10);
    snprintf(itemY4_Buf, 32, "%ld", g_year%10);
    snprintf(itemM_Buf, 32, "%01ld", g_month/10);
    snprintf(itemM2_Buf, 32, "%ld", g_month%10);
    snprintf(itemD_Buf, 32, "%01ld", g_day/10);
    snprintf(itemD2_Buf, 32, "%ld", g_day%10);
    snprintf(itemHR_Buf, 32, "%01ld", g_hour/10);
    snprintf(itemHR2_Buf, 32, "%ld", g_hour%10);
    snprintf(itemMIN_Buf, 32, "%01ld", g_min/10);
    snprintf(itemMIN2_Buf, 32, "%ld", g_min%10);
    snprintf(itemSEC_Buf, 32, "%02ld", g_second);

    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_YCtrl, STATIC_VALUE, Txt_Pointer(itemY_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_Y2Ctrl, STATIC_VALUE, Txt_Pointer(itemY2_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_Y3Ctrl, STATIC_VALUE, Txt_Pointer(itemY3_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_Y4Ctrl, STATIC_VALUE, Txt_Pointer(itemY4_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_MCtrl, STATIC_VALUE, Txt_Pointer(itemM_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_M2Ctrl, STATIC_VALUE, Txt_Pointer(itemM2_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_DCtrl, STATIC_VALUE, Txt_Pointer(itemD_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_D2Ctrl, STATIC_VALUE, Txt_Pointer(itemD2_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_HRCtrl, STATIC_VALUE, Txt_Pointer(itemHR_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_HR2Ctrl, STATIC_VALUE, Txt_Pointer(itemHR2_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_MINCtrl, STATIC_VALUE, Txt_Pointer(itemMIN_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_MIN2Ctrl, STATIC_VALUE, Txt_Pointer(itemMIN2_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_VALUE_Other0Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_VALUE_Other1Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndSetupDateTime_YMD_VALUE_Other2Ctrl, STATIC_VALUE, Txt_Pointer(itemOther2_Buf));
    ShowActiveSetting = TRUE;
    UxCtrl_SetShow(g_pActiveSettingCtrl, ShowActiveSetting);
    UxCtrl_SetDirty(&UIMenuWndSetupDateTime_TabCtrl, TRUE);
}

INT32 UIMenuWndSetupDateTime_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    RTC_DATE    Date;
    RTC_TIME    Time;

    Date = rtc_getDate();
    Time = rtc_getTime();
    g_year = Date.s.year;
    g_month = Date.s.month;
    g_day = Date.s.day;
    g_hour = Time.s.hour;
    g_min = Time.s.minute;
    g_second = Time.s.second;
    g_pActiveSettingCtrl = &UIMenuWndSetupDateTime_YMD_PNL_YCtrl;

    g_uiBlinkTimerID = GxTimer_StartTimer (TIMER_HALF_SEC, NVTEVT_05SEC_TIMER, CONTINUE);

    UxCtrl_SetShow(&UIMenuWndSetupDateTime_YMD_PNL_YCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupDateTime_YMD_PNL_MCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupDateTime_YMD_PNL_DCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupDateTime_YMD_PNL_HRCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupDateTime_YMD_PNL_MINCtrl, TRUE);
    UIMenuWndSetupDateTime_UpdateInfo();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDateTime_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(g_uiBlinkTimerID != NULL_TIMER)
        GxTimer_StopTimer(&g_uiBlinkTimerID);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupDateTime_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
        case NVTEVT_05SEC_TIMER:
            UxCtrl_SetShow(g_pActiveSettingCtrl, ShowActiveSetting);
            ShowActiveSetting = ShowActiveSetting?FALSE:TRUE;
            break;
        default:
            break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupDateTime_OnTouchPanelSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupDateTimeCtrl,0);
    return NVTEVT_CONSUME;
}

//----------------------UIMenuWndSetupDateTime_TabCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_Tab)
EVENT_END

//----------------------UIMenuWndSetupDateTime_Tab_YMD_VALUECtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_Tab_YMD_VALUE)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_VALUE_Other0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_VALUE_Other0)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_VALUE_Other1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_VALUE_Other1)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_VALUE_Other2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_VALUE_Other2)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_OKCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_OK_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_OK)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_OK_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_OK_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    rtc_setDate(g_year, g_month, g_day);
    rtc_setTime(g_hour, g_min, g_second);
    rtc_triggerCSET();

    Ux_CloseWindow(&UIMenuWndSetupDateTimeCtrl,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_INCCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelHold(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_INC)
EVENT_ITEM(NVTEVT_HOLD,UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelHold)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelHold(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelClick(pCtrl, paramNum, paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupDateTime_YMD_INC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_YCtrl)
    {
        g_year++;
        if (g_year > DATETIME_MAX_YEAR)
        {
            g_year = DATETIME_DEFAULT_YEAR;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_MCtrl)
    {
        g_month++;
        if (g_month > 12)
        {
            g_month = 1;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_DCtrl)
    {
        g_day++;
        if (g_day > DayOfMonth[rtc_isLeapYear(g_year)][g_month-1])
        {
            g_day = 1;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_HRCtrl)
    {
        g_hour++;
        if (g_hour > 23)
        {
            g_hour = 0;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_MINCtrl)
    {
        g_min++;
        if (g_min > 59)
        {
            g_min = 0;
        }
    }
    UIMenuWndSetupDateTime_UpdateInfo();
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_DECCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelHold(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_DEC)
EVENT_ITEM(NVTEVT_HOLD,UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelHold)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelHold(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelClick(pCtrl, paramNum, paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupDateTime_YMD_DEC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_YCtrl)
    {
        g_year--;
        if (g_year < DATETIME_DEFAULT_YEAR)
        {
            g_year = DATETIME_MAX_YEAR;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_MCtrl)
    {
        g_month--;
        if (g_month < 1)
        {
            g_month = 12;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_DCtrl)
    {
        g_day--;
        if (g_day < 1)
        {
            g_day = DayOfMonth[rtc_isLeapYear(g_year)][g_month-1];
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_HRCtrl)
    {
        if (g_hour == 0)
        {
            g_hour = 23;
        }
        else
        {
            g_hour--;
        }
    }
    else if (g_pActiveSettingCtrl == &UIMenuWndSetupDateTime_YMD_PNL_MINCtrl)
    {
        if (g_min == 0)
        {
            g_min = 59;
        }
        else
        {
            g_min--;
        }
    }
    UIMenuWndSetupDateTime_UpdateInfo();
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupDateTime_YMD_PNL_YCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_Y)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_Y)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_Y2)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_Y3)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_Y4)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTime_YMD_PNL_YCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_PNL_Y_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_Y)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_PNL_Y_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_PNL_Y_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(g_pActiveSettingCtrl, TRUE);
    g_pActiveSettingCtrl = pCtrl;
    UxCtrl_SetShow(g_pActiveSettingCtrl, FALSE);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_YCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_Y)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_Y2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_Y2)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_Y3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_Y3)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_Y4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_Y4)
EVENT_END

//---------------------UIMenuWndSetupDateTime_YMD_PNL_MCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_M)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_M)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_M2)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTime_YMD_PNL_MCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_PNL_M_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_M)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_PNL_M_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_PNL_M_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(g_pActiveSettingCtrl, TRUE);
    g_pActiveSettingCtrl = pCtrl;
    UxCtrl_SetShow(g_pActiveSettingCtrl, FALSE);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_MCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_M)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_M2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_M2)
EVENT_END

//---------------------UIMenuWndSetupDateTime_YMD_PNL_DCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_D)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_D)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_D2)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTime_YMD_PNL_DCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_PNL_D_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_D)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_PNL_D_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_PNL_D_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(g_pActiveSettingCtrl, TRUE);
    g_pActiveSettingCtrl = pCtrl;
    UxCtrl_SetShow(g_pActiveSettingCtrl, FALSE);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_DCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_D)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_D2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_D2)
EVENT_END

//---------------------UIMenuWndSetupDateTime_YMD_PNL_HRCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_HR)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_HR)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_HR2)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTime_YMD_PNL_HRCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_PNL_HR_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_HR)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_PNL_HR_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_PNL_HR_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(g_pActiveSettingCtrl, TRUE);
    g_pActiveSettingCtrl = pCtrl;
    UxCtrl_SetShow(g_pActiveSettingCtrl, FALSE);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_HRCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_HR)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_HR2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_HR2)
EVENT_END

//---------------------UIMenuWndSetupDateTime_YMD_PNL_MINCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_MIN)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_MIN)
CTRL_LIST_ITEM(UIMenuWndSetupDateTime_YMD_MIN2)
CTRL_LIST_END

//----------------------UIMenuWndSetupDateTime_YMD_PNL_MINCtrl Event---------------------------
INT32 UIMenuWndSetupDateTime_YMD_PNL_MIN_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_PNL_MIN)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupDateTime_YMD_PNL_MIN_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupDateTime_YMD_PNL_MIN_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(g_pActiveSettingCtrl, TRUE);
    g_pActiveSettingCtrl = pCtrl;
    UxCtrl_SetShow(g_pActiveSettingCtrl, FALSE);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDateTime_YMD_MINCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_MIN)
EVENT_END

//----------------------UIMenuWndSetupDateTime_YMD_MIN2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDateTime_YMD_MIN2)
EVENT_END

