#ifndef YUANDOGETCCONFIG_H__
#define YUANDOGETCCONFIG_H__

//#define YUANDOG_LANGUAGE_ENGLISH	
#define YUANDOG_LANGUAGE_CHINESE

#define YUANDOG_SOFTWARE_TRIAL

//#define YUANDOG_SIMULATOR_NMEA_DATA
#define YUANDOG_VARIABLE_DISTANCE_REPORT
//#define YUANDOG_SUPPORT_TTS

#define YUANDOG_DISABLE_MENU_VOICE

#define YUANDOG_DEBUG_LOG

#ifdef YUANDOG_DEBUG_LOG
	#define _DEBUG_LOG_
//	#define _DEBUG_RSSI_
#endif

#define YUANDOG_SUPPORT_DVR

#ifdef YUANDOG_SUPPORT_DVR
	#define YUANDOG_SUPPORT_DVR_SQ

	//#define YUANDOG_SUPPORT_DVR_ESCAPE

	// one of below two item
	#define YUANDOG_SUPPORT_DVR_UART
	//#define YUANDOG_SUPPORT_DVR_USB

	#ifdef YUANDOG_SUPPORT_DVR_USB
		#undef YUANDOG_DEBUG_LOG
		#undef _DEBUG_LOG_
		#undef _DEBUG_RSSI_
	#endif

	// one of below three item
	//#define YUANDOG_SUPPORT_DVR_SINGLE_NMEA
	#define YUANDOG_SUPPORT_DVR_NONE_NMEA
	//#define YUANDOG_SUPPORT_DVR_ALL

	#if defined(YUANDOG_SUPPORT_DVR_ALL) || defined(YUANDOG_SUPPORT_DVR_SINGLE_NMEA)
		// one of below two item
		//#define YUANDOG_SUPPORT_DVR_NMEA_GPRMC
		#define YUANDOG_SUPPORT_DVR_NMEA_STANDARD
	#endif

#endif //YUANDOG_SUPPORT_DVR

#define YUANDOG_SUPPORT_LED


#endif
