//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMOBILELINKOK_H
#define UIMENUWNDWIFIMOBILELINKOK_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiMobileLinkOKCtrl;//Panel type 

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl;//Static type 

extern VControl UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl;//Button type 

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl;//Static type 

extern VControl UIMenuWndWiFiMobile_StatusICN_WiFiCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiMobile_StatusICN_WiFi_ICON_WIFI_ON,
UIMenuWndWiFiMobile_StatusICN_WiFi_MAX
}UIMenuWndWiFiMobile_StatusICN_WiFi_Setting;

extern VControl UIMenuWndWiFiMobileLinkOK_Status_RECCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiMobileLinkOK_Status_REC_ICON_REC_TRANSPAENT,
UIMenuWndWiFiMobileLinkOK_Status_REC_ICON_REC_ELLIPSE,
UIMenuWndWiFiMobileLinkOK_Status_REC_MAX
}UIMenuWndWiFiMobileLinkOK_Status_REC_Setting;

//---------------------UIMenuWndWiFiMobileLinkOKCtrl User Export---------------------------
#endif
