#ifndef _IPL_CTRLINFOR_INT_H_
#define _IPL_CTRLINFOR_INT_H_

#ifndef _IPL_COM_INT_INC
    #error "illegal include IPL common module internal .H file"
#endif

/**
    IPL_CtrlInfor_Int.h


    @file       IPL_CtrlInfor_Int.h
    @ingroup    mISYSAlg
    @note       Nothing (or anything need to be mentioned).

    Copyright   Novatek Microelectronics Corp. 2011.  All rights reserved.
*/
#include "Type.h"
#include "ErrorNo.h"

/**
    default information for Image-Pipeline
*/
typedef enum
{
    IPLCTRL_PRVFLOW = 0,
    IPLCTRL_CAPFLOW,

    IPLCTRL_CFMODE,     //IPL_CF_NORMAL, IPL_CF_CCIR, IPL_CF_RHEHDR, IPL_CF_2STRP, IPL_CF_RHEWDR, IPL_CF_2STRP_F
    IPLCTRL_CFMODEEXT,  //IPL_CFEXT_NORMAL, IPL_CFEXT_SIE_ONLY, IPL_CFEXT_DEINTERLACE, IPL_CFEXT_DEINTERLACE2, IPL_CFEXT_SYNCTRIG, IPL_CFEXT_IMESCALE, IPL_CFEXT_ISESCALE

    IPLCTRL_PRVBURSTLENGTH,
    IPLCTRL_CAPBURSTLENGTH,

    IPLCTRL_CUR_MODE,

    IPLCTRL_SEN_PRVCROPRATIO,
    IPLCTRL_SEN_CAPCROPRATIO,

    IPLCTRL_SIE_CH3_CAP_SUBRATIO,

    IPLCTRL_PRVAUTO_OB_EN,
    IPLCTRL_CAPAUTO_OB_EN,
    IPLCTRL_CAPDF_EN,

    IPLCTRL_SIE_PRVSTPIX,
    IPLCTRL_SIE_CH0_PRVBIT,
    IPLCTRL_SIE_CH3_PRVBIT,

    IPLCTRL_SIE_CAPSTPIX,
    IPLCTRL_SIE_CH0_CAPBIT,
    IPLCTRL_SIE_CH3_CAPBIT,

    IPLCTRL_SIE_PRVCROP_SIZE_H,
    IPLCTRL_SIE_PRVCROP_SIZE_V,

    IPLCTRL_SIE_CAPCROP_SIZE_H,
    IPLCTRL_SIE_CAPCROP_SIZE_V,

    IPLCTRL_SIE_CH0_RAWENC_EN,
    IPLCTRL_SIE_DISABLE_RAWENC_MANUAL,  //RAW ENCODE ON/OFF Switch, only for debug using

    IPLCTRL_SIE_CH0_RAW_EN,
    IPLCTRL_SIE_CH0_RAW_BUFNUM,
    IPLCTRL_SIE_CH0_RAW_SIZE_H,
    IPLCTRL_SIE_CH0_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH0_RAW_SIZE_V,
    IPLCTRL_SIE_CH0_RAW_1STSTRP_LOS,

    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_H,
    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_V,

    IPLCTRL_SIE_CH1_Y_EN,
    IPLCTRL_SIE_CA_EN,

    IPLCTRL_SIE_CH1_BUFNUM,
    IPLCTRL_SIE_CH1_H_FLIP,
    IPLCTRL_SIE_CH1_V_FLIP,
    IPLCTRL_SIE_CA_WINXNUM,
    IPLCTRL_SIE_CA_WINYNUM,


    IPLCTRL_SIE_CH2_UV_EN,
    IPLCTRL_SIE_LA_EN,

    IPLCTRL_SIE_CH2_BUFNUM,
    IPLCTRL_SIE_CH2_H_FLIP,
    IPLCTRL_SIE_CH2_V_FLIP,
    IPLCTRL_SIE_LA_WINXNUM,
    IPLCTRL_SIE_LA_WINYNUM,

    IPLCTRL_SIE_CH3_RAW_EN,
    IPLCTRL_SIE_CH3_RAW_BUFNUM,
    IPLCTRL_SIE_CH3_RAW_SIZE_H,
    IPLCTRL_SIE_CH3_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH3_RAW_SIZE_V,
    IPLCTRL_SIE_CH3_CAP_RAW_SIZE_H,
    IPLCTRL_SIE_CH3_CAP_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH3_CAP_RAW_SIZE_V,

    IPLCTRL_SIE_VA_EN,
    IPLCTRL_SIE_VA_BUFNUM,

    IPLCTRL_SIE_ETH_EN,
    IPLCTRL_SIE_ETH_SIZE_H,
    IPLCTRL_SIE_ETH_SIZE_HLOS,
    IPLCTRL_SIE_ETH_SIZE_V,

    IPLCTRL_SIE_ECS_EN,

    IPLCTRL_IPL_IN_BIT,
    IPLCTRL_IPL_IN_SIZE_H,
    IPLCTRL_IPL_IN_SIZE_HLOS,
    IPLCTRL_IPL_IN_SIZE_V,

    IPLCTRL_IFE_DMA_IN_EN,
    IPLCTRL_IFE_IN_BIT,
    IPLCTRL_IFE_IN_STPIX,
    IPLCTRL_IFE_IN_SIZE_H,
    IPLCTRL_IFE_IN_SIZE_HLOS,
    IPLCTRL_IFE_IN_SIZE_V,

    IPLCTRL_IPE_OUT_EN,
    IPLCTRL_IPE_IFE2_EN,

    IPLCTRL_IPE_OUT_FMT,
    IPLCTRL_IPE_OUT_BUFNUM,
    IPLCTRL_IPE_OUT_SIZE_H,
    IPLCTRL_IPE_OUT_SIZE_V,
    IPLCTRL_IPE_OUT_SIZE_YLOS,

    IPLCTRL_IPE_CAP_SUBRATIO,

    IPLCTRL_IFE2_LCA_EN,
    IPLCTRL_IFE2_OUT_BUFNUM,
    IPLCTRL_IFE2_OUT_SIZE_YLOS,
    IPLCTRL_IFE2_OUT_SIZE_CLOS,

    IPLCTRL_IME_P1_EN,
    IPLCTRL_IME_P1_D2H264,
    IPLCTRL_IME_P1_FMT,
    IPLCTRL_IME_P1_BUFFMT,
    IPLCTRL_IME_P1_BUFNUM,
    IPLCTRL_IME_P1_BUF_SIZE_H,
    IPLCTRL_IME_P1_BUF_SIZE_V,
    IPLCTRL_IME_P1_OUT_SIZE_H,
    IPLCTRL_IME_P1_OUT_SIZE_HLOS,
    IPLCTRL_IME_P1_OUT_SIZE_V,
    IPLCTRL_IME_P1_OUT_CROP_STR_X,
    IPLCTRL_IME_P1_OUT_CROP_STR_Y,
    IPLCTRL_IME_P1_OUT_CROP_H,
    IPLCTRL_IME_P1_OUT_CROP_V,
    IPLCTRL_IME_P1_SPRT_YBUFOFS,
    IPLCTRL_IME_P1_SPRT_CBUFOFS,

    IPLCTRL_IME_P2_EN,
    IPLCTRL_IME_P2_FMT,
    IPLCTRL_IME_P2_BUFFMT,
    IPLCTRL_IME_P2_BUFNUM,
    IPLCTRL_IME_P2_BUF_SIZE_H,
    IPLCTRL_IME_P2_BUF_SIZE_V,
    IPLCTRL_IME_P2_OUT_SIZE_H,
    IPLCTRL_IME_P2_OUT_SIZE_HLOS,
    IPLCTRL_IME_P2_OUT_SIZE_V,
    IPLCTRL_IME_P2_OUT_CROP_STR_X,
    IPLCTRL_IME_P2_OUT_CROP_STR_Y,
    IPLCTRL_IME_P2_OUT_CROP_H,
    IPLCTRL_IME_P2_OUT_CROP_V,
    IPLCTRL_IME_P2_SPRT_YBUFOFS,
    IPLCTRL_IME_P2_SPRT_CBUFOFS,

    IPLCTRL_IME_P3_EN,
    IPLCTRL_IME_P3_FMT,
    IPLCTRL_IME_P3_BUFFMT,
    IPLCTRL_IME_P3_BUFNUM,
    IPLCTRL_IME_P3_BUF_SIZE_H,
    IPLCTRL_IME_P3_BUF_SIZE_V,
    IPLCTRL_IME_P3_OUT_SIZE_H,
    IPLCTRL_IME_P3_OUT_SIZE_HLOS,
    IPLCTRL_IME_P3_OUT_SIZE_V,
    IPLCTRL_IME_P3_OUT_CROP_STR_X,
    IPLCTRL_IME_P3_OUT_CROP_STR_Y,
    IPLCTRL_IME_P3_OUT_CROP_H,
    IPLCTRL_IME_P3_OUT_CROP_V,
    IPLCTRL_IME_P3_SPRT_YBUFOFS,
    IPLCTRL_IME_P3_SPRT_CBUFOFS,

    IPLCTRL_IME_P4_EN,
    IPLCTRL_IME_P4_FMT,
    IPLCTRL_IME_P4_BUFFMT,
    IPLCTRL_IME_P4_BUFNUM,
    IPLCTRL_IME_P4_BUF_SIZE_H,
    IPLCTRL_IME_P4_BUF_SIZE_V,
    IPLCTRL_IME_P4_OUT_SIZE_H,
    IPLCTRL_IME_P4_OUT_SIZE_HLOS,
    IPLCTRL_IME_P4_OUT_SIZE_V,
    IPLCTRL_IME_P4_OUT_CROP_STR_X,
    IPLCTRL_IME_P4_OUT_CROP_STR_Y,
    IPLCTRL_IME_P4_OUT_CROP_H,
    IPLCTRL_IME_P4_OUT_CROP_V,
    IPLCTRL_IME_P4_EXTOUT_EN,
    IPLCTRL_IME_P4_EDGEMAP_BUFOFS,
    IPLCTRL_IME_P4_HISTO_BUFOFS,

    IPLCTRL_DIS_EN,
    IPLCTRL_DIS_RATIO,

    IPLCTRL_MSNR_CAP_EN,

    IPLCTRL_EXT_FUNC_EN,

    IPLCTRL_SENSOR_TYPE,

    IPLCTRL_FLIP_TYPE,

    IPLCTRL_WDR_VER,

    IPLCTRL_VR360_EN,
    IPLCTRL_VR360_ORI_L,
    IPLCTRL_VR360_ORI_R,
    IPLCTRL_VR360_IMG_HEI_ADJ,
    IPLCTRL_VR360_IME_P1_START_OFS,
    IPLCTRL_VR360_IME_P2_START_OFS,
    IPLCTRL_VR360_IME_P3_START_OFS,

    IPLCTRL_SBS_TYPE,

    IPLCTRL_MAX_CNT_DEF,
    ENUM_DUMMY4WORD(IPLCTRL_IDX_DEF)
} IPLCTRL_IDX_DEF;

#define IPL_CTRL_ELEMENT_MAX 200
#define IPL_CTRL_NO_USE 0xffffffff

/**
     set ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @param[in] UINT32 value
*/
extern void IPL_CtrlSetInfor(UINT32 Id, UINT32 Idx, UINT32 Value);

/**
     get ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @return [UINT32]
         - @b value
*/
extern UINT32 IPL_CtrlGetInfor(UINT32 Id, UINT32 Idx);

/**
     initial ctrl information

     @note reset all array information.
     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforInit(void);

/**
     un-initial ctrl information

     @note reset all array information.

     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforUnInit(void);

#endif //_IPL_CTRLINFOR_INT_H_
