//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"
#include "UIFlowWndPlayMagnify.h"
#include "AppCommon.h"
#include "Audio.h"
#include "UICommon.h"
#include "UIFlow.h"
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
#include "SMediaPlayAPI.h"
#include "DCF.h"
#include "UIAppMoviePlay.h"
//#NT#2012/08/31#Calvin Chang -end
#include "UIAppPlay.h"
#include "UIPlayComm.h"
#include "FileDB.h"

#define __MODULE__          UIFlowWndPlay
//#define __DBGLVL__ 0        //OFF mode, show nothing
#define __DBGLVL__ 1        //ERROR mode, show err, wrn only
//#define __DBGLVL__ 2        //TRACE mode, show err, wrn, ind, msg and func and ind, msg and func can be filtering by __DBGFLT__ settings
#define __DBGFLT__ "*"      //*=All
#include "DebugModule.h"

// Photo mode key mask
#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      FLGKEY_KEY_MASK_NULL//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT

#define FULL_FILE_PATH_LEN      64

BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
UINT32         g_uiUIFlowWndPlayCurrentVolume   = AUDIO_VOL_5;
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
SMEDIAPLAY_USEROBJ  g_UIPlayMediaObj                 = {0};
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;
//#NT#2012/08/31#Calvin Chang -end

static INT32  g_TouchPressX                     = 0;
static INT32  g_TouchPressY                     = 0;

typedef enum
{
CLICK_FROM_NONE,
CLICK_FROM_BTN_PLAYPAUSE,
CLICK_FROM_BTN_THUMBNAIL,
CLICK_FROM_BTN_DELETE,
CLICK_FROM_BTN_RETURN
} CLICKFROM;
static CLICKFROM   g_ClickFrom                  = CLICK_FROM_NONE;

//---------------------UIFlowWndPlayCtrl Function ---------------------------
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);
//#NT#2012/08/31#Calvin Chang -end

//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Flash)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_EV)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Size)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_WB)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Quality)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Sharpness)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Storage)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Battery)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Date)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Time)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Pause)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_DscMode)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Setup)
CTRL_LIST_ITEM(UIFlowWndPlay_PNL_Control4)
CTRL_LIST_ITEM(UIFlowWndPlay_PNL_Control2)
#if (_KEY_METHOD_ == _KEY_METHOD_2KEY_)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_LeftBtn)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_RightBtn)
#endif
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelSlideUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelSlideDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelSlideLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelSlideRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndPlay_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndPlay_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndPlay_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPlay_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndPlay_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW,UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH,UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC,UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndPlay_OnStorageChange)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlay_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_SLIDE_UP,UIFlowWndPlay_OnTouchPanelSlideUp)
EVENT_ITEM(NVTEVT_SLIDE_DOWN,UIFlowWndPlay_OnTouchPanelSlideDown)
EVENT_ITEM(NVTEVT_SLIDE_LEFT,UIFlowWndPlay_OnTouchPanelSlideLeft)
EVENT_ITEM(NVTEVT_SLIDE_RIGHT,UIFlowWndPlay_OnTouchPanelSlideRight)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndPlay_OnTimer)
EVENT_END

static void UIFlowWndPlay_CheckStatus(void)
{
    UINT32 uiStatus, uiCurrMode;
    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
    PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

    // Decode Error & Read Error
    if( uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE) )
    {
        if(uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG)
        {
            UINT32  uiBuffAddr, uiBuffSize;
            CHAR    chaFullName[64] = { 0 };

            PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
            PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
            PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
            SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
            FileDB_Refresh(0);//2016/04/11
            debug_msg("^RSMediaPlay_FileRecovery is skipped.\r\n");
            uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
            if( uiStatus == PB_STA_DONE)
                return;
        }
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_PICTURE_ERR,FLOWWRNMSG_TIMER_2SEC);
    }
}

#if 0
static INT32 UIFlowWndPlay_OnExeUpKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiCurrMode;
    PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            if (uiCurrMode == PLAYMODE_PRIMARY && PB_WaitCommandFinish(PB_WAIT_INFINITE) == PB_STA_DONE)
            {
                Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
            }
            break;
        case PLB_ST_PLAY_MOV:
                if (g_uiUIFlowWndPlayCurrentVolume < AUDIO_VOL_7)
                {
                    // Start to Play
                    g_uiUIFlowWndPlayCurrentVolume++;
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                    //Ux_SendEvent(&CustomMoviePlayObjCtrl,
                    //             NVTEVT_EXE_STARTPLAY,
                    //             2,
                    //             g_uiUIFlowWndPlayCurrenSpeed,
                    //             g_uiUIFlowWndPlayCurrenDirection);
                    FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                }
            break;

    }
    return NVTEVT_CONSUME;
}

static INT32 UIFlowWndPlay_OnExeDownKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiActKey;

    if (paramNum >= 1)
        uiActKey = paramArray[0];
    else {
        debug_msg("error parameter!!\r\n");
        return NVTEVT_CONSUME;
    }

    switch (uiActKey)
    {
      case NVTEVT_KEY_PRESS:
           switch(g_PlbData.State)
            {
                case PLB_ST_FULL:
                    Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
                    break;
                case PLB_ST_PLAY_MOV:
                        if (g_uiUIFlowWndPlayCurrentVolume > AUDIO_VOL_MUTE)
                        {
                            // Start to Play
                            g_uiUIFlowWndPlayCurrentVolume--;
                            Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                            //Ux_SendEvent(&CustomMoviePlayObjCtrl,
                            //             NVTEVT_EXE_STARTPLAY,
                            //             2,
                            //             g_uiUIFlowWndPlayCurrenSpeed,
                            //             g_uiUIFlowWndPlayCurrenDirection);
                            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                        }
                    break;
            }
        break;
    }
    return NVTEVT_CONSUME;
}
#endif

INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiStatus;
    UINT32 uiFileNum = 0;

    g_bUIFlowWndPlayNoImgWndOpened = FALSE;

    PB_WaitCommandFinish(PB_WAIT_INFINITE);
    //After playback ready, point to the last file
    PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
//    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
    PB_OpenSpecFileBySeq(uiFileNum, TRUE);
    UIPlay_PlaySingle(PB_SINGLE_CURR);
    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

    //disable video2 and enable video 1
    Display_ShowPreview();

    UpdateVdoWinForPB();

    if (uiStatus & PB_STA_NOIMAGE)
    //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
    {
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_2SEC);
        g_bUIFlowWndPlayNoImgWndOpened = TRUE;
    }
    else
    {
        g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
        g_PlbData.State = PLB_ST_FULL;
        UIFlowWndPlay_CheckStatus();
        FlowPB_PanelEnablePNLContrl(0);
        FlowPB_UpdateIcons(1);
    }

    // Set mask key
    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
    Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
    Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
    Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            g_PlbData.State        = PLB_ST_FULL;
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_CLOSEPLAY, 0);

            if (gphUIFlowMovPlay_Filehdl)
            {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
            }
            break;
    }

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end
    //g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiStatus;

    //#NT#2012/12/27#Hideo Lin -begin
    //#NT#Fix close child window hang up as card removed
    if(Ux_IsForceCloseWindow())
    {
        return NVTEVT_CONSUME;
    }
    //#NT#2012/12/27#Hideo Lin -end

    if(paramNum > 0)
    {
        //Return from thumbnail, magnify or delete mode and play current image again.
        switch(paramArray[0])
        {
        case NVTRET_THUMBNAIL:
        case NVTRET_MAGNIFY:
            UIPlay_PlaySingle(PB_SINGLE_CURR);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            break;
        case NVTRET_DELETE:
        case NVTRET_DELETEALL:
            uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

            if (uiStatus & PB_STA_NOIMAGE)
            //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
            {
                if(!g_bUIFlowWndPlayNoImgWndOpened)
                {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_2SEC);
                    g_bUIFlowWndPlayNoImgWndOpened = TRUE;
                }
            }
            else
            {
                UIPlay_PlaySingle(PB_SINGLE_CURR);
                FlowPB_UpdateIcons(1);
                UIFlowWndPlay_CheckStatus();
            }
            break;
        case NVTRET_ENTER_MENU:
            // Reset specific menu items
            SysSetFlag(FL_PROTECT, PROTECT_ONE);
            // Open common item menu
            Ux_OpenWindow((VControl *)(&MenuCommonItemCtrl), 1, &gMenuModeTouch);
            g_bUIFlowWndPlayNoImgWndOpened = FALSE;
            break;
        case NVTRET_WARNING:
            Ux_PostEvent(paramArray[1], 0);
            break;
        }
    }
    else
    {
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
        if (uiStatus & PB_STA_NOIMAGE)
        //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
        {
            if(!g_bUIFlowWndPlayNoImgWndOpened && !g_NeedOpenSetupMode)  // If the UI flow comes from Mode->Setup, no need show warning message.
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_2SEC);
                g_bUIFlowWndPlayNoImgWndOpened = TRUE;
            }
            else
            {
                Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
                // Reset specific menu items
                SysSetFlag(FL_PROTECT, PROTECT_ONE);
                // Open common item menu
                g_PlbData.State = PLB_ST_MENU;
                g_bUIFlowWndPlayNoImgWndOpened = FALSE;
                Ux_OpenWindow((VControl *)(&MenuCommonItemCtrl), 1, &gMenuModeTouch);
                Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
            }
        }
        else//file error
        {
            //UIPlay_PlaySingle(PB_SINGLE_CURR);
            FlowPB_UpdateIcons(1);
            //UIFlowWndPlay_CheckStatus();
        }
    }

    switch (g_PlbData.State)
    {
        case PLB_ST_MENU:
            if (g_NeedOpenSetupMode == TRUE)
            {
                g_NeedOpenSetupMode = FALSE;
                g_PlbData.State = PLB_ST_MENU;
                Ux_OpenWindow (&MenuCommonItemCtrl, 1, &gSetupMenu);
            }
            else
            {
                g_PlbData.State = PLB_ST_FULL;
            }
            break;
        default:
            g_PlbData.State = PLB_ST_FULL;
    }

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone flag
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end

    // set mask key
    //Ux_FlushEvent();
    Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
    Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
    Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  static volatile BOOL bBatteryOn = FALSE;

    UxState_SetData(&UIFlowWndPlay_StatusICN_BatteryCtrl,STATE_CURITEM,GetBatteryLevel());
    if (KeyScan_IsACIn())
    {
        bBatteryOn = !bBatteryOn;
        UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl,bBatteryOn);
    } else {
        UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl,TRUE);
    }

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
    g_PlbData.State        = PLB_ST_FULL;
    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_CLOSEPLAY, 0);

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable key tone flag
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end

    // stop scan
    //if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

    if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID)==0)
        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);


    if (gphUIFlowMovPlay_Filehdl)
    {
        FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
        gphUIFlowMovPlay_Filehdl = NULL;
    }

    // Play 1st video frame image
    UIPlay_PlaySingle(PB_SINGLE_CURR);
    //#NT#2012/08/31#Calvin Chang -end

    FlowPB_UpdateIcons(1);
    FlowPB_PanelEnablePNLContrl(0);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    FlowPB_IconDrawMovPlayTime(TRUE);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_TouchPressX = paramArray[0];
    g_TouchPressY = paramArray[1];
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiPosX;
    INT32 uiPosY;

    uiPosX = paramArray[0];
    uiPosY = paramArray[1];

    if ((UxCtrl_IsShow(&UIFlowWndPlay_PNL_Control4Ctrl) == FALSE) && (g_PlbData.State == PLB_ST_FULL))
    {
        //if ((g_TouchPressY > DISPLAY_OSD_H - (DISPLAY_OSD_H /5)) && ((g_TouchPressY - uiPosY) > (DISPLAY_OSD_H / 3)))
        if (g_TouchPressY > (DISPLAY_OSD_H - (DISPLAY_OSD_H / 3)))              // Only check start position
        {
            g_PlbData.State = PLB_ST_MENU;
            Ux_OpenWindow(&MenuCommonItemCtrl, 1, &gPlaybackMenu);
        }
    }
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelSlideDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiPosX;
    INT32 uiPosY;

    uiPosX = paramArray[0];
    uiPosY = paramArray[1];

    if ((UxCtrl_IsShow(&UIFlowWndPlay_PNL_Control4Ctrl) == FALSE) && (g_PlbData.State == PLB_ST_FULL))
    {
        //if ((g_TouchPressY < (DISPLAY_OSD_H /5)) && ((uiPosY - g_TouchPressY) > (DISPLAY_OSD_H / 3)))
        if (g_TouchPressY < (DISPLAY_OSD_H / 3))                                // Only check start position
        {
            g_PlbData.State = PLB_ST_MENU;
            Ux_OpenWindow((VControl *)(&MenuCommonItemCtrl), 1, &gMenuModeTouch);
        }
    }
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelSlideLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if ((UxCtrl_IsShow(&UIFlowWndPlay_PNL_Control4Ctrl) == FALSE) && (g_PlbData.State == PLB_ST_FULL))
    {
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
        UIPlay_PlaySingle(PB_SINGLE_PREV);
        FlowPB_UpdateIcons(1);
        UIFlowWndPlay_CheckStatus();
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    }
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelSlideRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if ((UxCtrl_IsShow(&UIFlowWndPlay_PNL_Control4Ctrl) == FALSE) && (g_PlbData.State == PLB_ST_FULL))
    {
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
        UIPlay_PlaySingle(PB_SINGLE_NEXT);
        FlowPB_UpdateIcons(1);
        UIFlowWndPlay_CheckStatus();
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    }
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiStatus;
    UINT32 uiPoolAddr;
    char   pFilePath[FULL_FILE_PATH_LEN];
    UINT32 fileType = DCF_FILE_TYPE_JPG;
    UINT32 uiPBFileFmt;

    switch (g_ClickFrom)
    {
        case CLICK_FROM_NONE:
            switch (g_PlbData.State)
            {
                case PLB_ST_FULL:
                    ResetAutoHideTimer();
                    FlowPB_UpdateIcons(FALSE);
                    FlowPB_PanelEnablePNLContrl(4);
                    break;
                case PLB_ST_PLAY_MOV:
                case PLB_ST_PAUSE_MOV:
                    ResetAutoHideTimer();
                    PB_GetParam(PBPRMID_CURR_FILEFMT, &uiStatus);
                    if (uiStatus & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS))
                    {
                        PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiStatus);
                        if(uiStatus == PLAYMODE_PRIMARY)
                        {
                            StopAutoHideTimer();
                            g_PlbData.State = PLB_ST_FULL;
                            FlowPB_UpdateIcons(1);
                        }
                        else
                        {
                            FlowPB_PanelEnablePNLContrl(2);
                        }
                    }
                    break;
                case PLB_ST_MAGNIFY:
                    StopAutoHideTimer();
                    g_PlbData.State = PLB_ST_FULL;
                    FlowPB_UpdateIcons(1);
                    break;
                default:
                    break;
            }
            break;
        case CLICK_FROM_BTN_PLAYPAUSE:
            StopAutoHideTimer();
            FlowPB_PanelEnablePNLContrl(0);
            switch(g_PlbData.State)
            {
                case PLB_ST_FULL:
                    PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
                    if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS))
                    {
                        // Open Video File
                        if (gphUIFlowMovPlay_Filehdl)
                        {
                            FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                            gphUIFlowMovPlay_Filehdl = NULL;
                        }
                        if (uiPBFileFmt & PBFMT_AVI)
                        {
                            fileType = DCF_FILE_TYPE_AVI;
                        }
                        else if (uiPBFileFmt & PBFMT_MOVMJPG)
                        {
                            fileType = DCF_FILE_TYPE_MOV;
                        }
                        else if (uiPBFileFmt & PBFMT_MP4)
                        {
                            fileType = DCF_FILE_TYPE_MOV;
                        }
                        else
                        {
                            debug_msg("Wrong video file format!! \r\n");
                            break;
                        }
                        // Get Current index
                        PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

                        // Open Test Media File
                        gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

                        if (!gphUIFlowMovPlay_Filehdl)
                        {
                            debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
                            break;
                        }
                        // disable auto power off/USB detect timer
                        // disable key tone flag
                        KeyScan_EnableMisc(FALSE);

                        // Buffer Allocation
                        get_blf((VP*)&(uiPoolAddr), POOL_ID_APP);
                        rel_blf(POOL_ID_APP, (VP)uiPoolAddr);

                        g_UIPlayMediaObj.hActMediafilehdl = gphUIFlowMovPlay_Filehdl;
                        g_UIPlayMediaObj.CallBackFunc     = Play_MovieCB;
                        g_UIPlayMediaObj.uiMemAddr        = (UINT32)OS_GetMempoolAddr(POOL_ID_APP);
                        g_UIPlayMediaObj.uiMemSize        = POOL_SIZE_APP;

                        UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                        g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                        //flush event first
                        Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                        //stop scan
                        //SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
                        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);
                        Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_OPENPLAY, 1, &g_UIPlayMediaObj);
                        // Start to Play
                        Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                     NVTEVT_EXE_STARTPLAY,
                                     2,
                                     g_uiUIFlowWndPlayCurrenSpeed,
                                     g_uiUIFlowWndPlayCurrenDirection);
                        //set movie volumn
                        Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,2,UI_GetData(FL_MovieAudioPlayIndex),1);
                        FlowPB_UpdateIcons(0);
                        g_PlbData.State = PLB_ST_PLAY_MOV;
                        FlowPB_IconDrawLeftBtn(TRUE);
                        FlowPB_IconDrawRightBtn(TRUE);
                        FlowPB_IconDrawMovPlayTime(TRUE);
                    }
                    else
                    {
                        g_PlbData.State = PLB_ST_MAGNIFY;
                        FlowPB_UpdateIcons(0);
                        FlowPB_IconDrawLeftBtn(TRUE);
                    }
                    break;
                case PLB_ST_PLAY_MOV:
                    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
                    g_PlbData.State = PLB_ST_PAUSE_MOV;
                    FlowPB_IconDrawPause(TRUE);
                    break;
                case PLB_ST_PAUSE_MOV:
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,2,UI_GetData(FL_MovieAudioPlayIndex),1);
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    FlowPB_IconDrawPause(FALSE);
                    break;
                default:
                    break;
            }
            break;
        case CLICK_FROM_BTN_THUMBNAIL:
            StopAutoHideTimer();
            FlowPB_PanelEnablePNLContrl(0);
            switch (g_PlbData.State)
            {
                case PLB_ST_FULL:
                    Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
                default:
                    break;
            }
            break;
        case CLICK_FROM_BTN_DELETE:
            StopAutoHideTimer();
            FlowPB_PanelEnablePNLContrl(0);
            switch (g_PlbData.State)
            {
                case PLB_ST_FULL:
                    //Ux_OpenWindow(&MenuCommonConfirmCtrl, 1,IDM_DELETE_THIS);
                    Ux_OpenWindow(&MenuCommonConfirmCtrl, 1,IDM_DELETE_THIS);
                default:
                    break;
            }
            break;
        case CLICK_FROM_BTN_RETURN:
            StopAutoHideTimer();
            FlowPB_PanelEnablePNLContrl(0);
            switch (g_PlbData.State)
            {
                case PLB_ST_FULL:
                    StopAutoHideTimer();
                    FlowPB_PanelEnablePNLContrl(0);
                    FlowPB_UpdateIcons(TRUE);
                    break;
                case PLB_ST_PLAY_MOV:
                case PLB_ST_PAUSE_MOV:
                    g_PlbData.State        = PLB_ST_FULL;
                    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
                    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_CLOSEPLAY, 0);
                    KeyScan_EnableMisc(TRUE);
                    if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID)==0)
                    {
                        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
                    }
                    if (gphUIFlowMovPlay_Filehdl)
                    {
                        FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                        gphUIFlowMovPlay_Filehdl = NULL;
                    }
                    UIPlay_PlaySingle(PB_SINGLE_CURR);
                    FlowPB_UpdateIcons(1);
                    break;
                case PLB_ST_MAGNIFY:
                    g_PlbData.State = PLB_ST_FULL;
                    FlowPB_UpdateIcons(1);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
    g_ClickFrom = CLICK_FROM_NONE;
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
        case NVTEVT_SELFTIMER:
            StopAutoHideTimer();
            FlowPB_PanelEnablePNLContrl(0);
            switch (g_PlbData.State)
            {
                case PLB_ST_FULL:
                    FlowPB_UpdateIcons(TRUE);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
    return NVTEVT_CONSUME;
}

//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
    switch (uiChangeSpeedLevel)
    {
        default:
        case PLB_FWD_MOV_1x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_NORMAL;
        break;

        case PLB_FWD_MOV_2x:
        case PLB_BWD_MOV_2x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_2X;
        break;

        case PLB_FWD_MOV_4x:
        case PLB_BWD_MOV_4x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_4X;
        break;

        case PLB_FWD_MOV_8x:
        case PLB_BWD_MOV_8x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_8X;
        break;

    }
}

//----------------------UIFlowWndPlay_StatusICN_FlashCtrl Event---------------------------
INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Flash)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlay_StatusICN_Flash_OnKeyRight)
EVENT_END

INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_EV)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SizeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Size)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_WBCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_WB)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_QualityCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Quality)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_SharpnessCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Sharpness)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Storage)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Battery)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_DateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Date)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_TimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Time)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_LeftBtnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_LeftBtn)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_RightBtnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_RightBtn)
EVENT_END

//----------------------UIFlowWndPlay_BTN_DscModeCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_DscMode_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_DscMode)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_DscMode_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_DscMode_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_PlbData.State == PLB_ST_FULL)
    {
        g_PlbData.State = PLB_ST_MENU;
        Ux_OpenWindow((VControl *)(&MenuCommonItemCtrl), 1, &gMenuModeTouch);
    }
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_SetupCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Setup_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_Setup)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Setup_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_Setup_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_PlbData.State == PLB_ST_FULL)
    {
        g_PlbData.State = PLB_ST_MENU;
        Ux_OpenWindow(&MenuCommonItemCtrl, 1, &gPlaybackMenu);
    }
    return NVTEVT_CONSUME;
}

//---------------------UIFlowWndPlay_PNL_Control4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_PNL_Control4)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Delete4)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_PlayPause4)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Thumbnail4)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Return4)
CTRL_LIST_END

//----------------------UIFlowWndPlay_PNL_Control4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_PNL_Control4)
EVENT_END

//----------------------UIFlowWndPlay_BTN_Delete4Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Delete4_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_Delete4)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Delete4_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_Delete4_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_DELETE;
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_PlayPause4Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_PlayPause4_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_PlayPause4)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_PlayPause4_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_PlayPause4_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_PLAYPAUSE;
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_Thumbnail4Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Thumbnail4_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_Thumbnail4)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Thumbnail4_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_Thumbnail4_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_THUMBNAIL;
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_Return4Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Return4_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_Return4)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Return4_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_Return4_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_RETURN;
    return NVTEVT_CONSUME;
}

//---------------------UIFlowWndPlay_PNL_Control2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_PNL_Control2)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_PlayPause2)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Return2)
CTRL_LIST_END

//----------------------UIFlowWndPlay_PNL_Control2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_PNL_Control2)
EVENT_END

//----------------------UIFlowWndPlay_BTN_PlayPause2Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_PlayPause2_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_PlayPause2)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_PlayPause2_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_PlayPause2_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_PLAYPAUSE;
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_Return2Ctrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Return2_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_Return2)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Return2_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_Return2_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_ClickFrom = CLICK_FROM_BTN_RETURN;
    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_StaticICN_PauseCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Pause)
EVENT_END
